import {randomUUID} from 'node:crypto';
import {sql,claimJob,finishJob,closeDatabase} from '../../packages/database/index';
import {negotiateCustom} from '../../packages/agents/custom-seller';
import {syncChainHistory} from '../../packages/server/history';
import {runBuyer,runSeller} from '../../packages/agents/index';
import {publishOffer,fundOrder,fulfillOrder,withdrawOrder,prepareOffer,resolveOrder,maintainOrders} from '../../packages/server/market';
import {activity} from '../../packages/server/index';
const owner=randomUUID();let stopped=false;process.on('SIGTERM',()=>{stopped=true});process.on('SIGINT',()=>{stopped=true});
console.log('SportProof durable worker starting; live errors never become fixture success');
while(!stopped){await sql()`INSERT INTO worker_health(id) VALUES(${owner}) ON CONFLICT(id) DO UPDATE SET heartbeat_at=now()`;const job=await claimJob(owner);if(!job){await maintainOrders().catch(()=>{});await syncChainHistory().catch(()=>{});await new Promise(r=>setTimeout(r,1000));continue}const renew=setInterval(()=>{void sql()`UPDATE jobs SET lease_until=now()+interval '90 seconds' WHERE id=${job.id} AND lease_owner=${owner}`},25000);try{const p=job.payload;switch(job.kind){case 'buyer':await runBuyer(p.missionId);break;case 'seller':await runSeller(p.tenantId);break;case 'publish':await publishOffer(p.offerId);break;case 'purchase':await fundOrder(p.orderId);break;case 'fulfill':await fulfillOrder(p.orderId);break;case 'withdraw':await withdrawOrder(p.orderId);break;case 'resolve':await resolveOrder(p.orderId);break;case 'custom':await negotiateCustom(p.requestId,p.tenantId,p.principalId,p.scope);break;default:throw new Error('Unsupported job type')}await finishJob(job.id,owner)}catch(error){const message=error instanceof Error?error.message:'Worker error';// Error text may originate upstream; persist a bounded category rather than provider payloads.
const safe=/OPENAI|ANTHROPIC|claude|provider|model|authentication|api.?key|invalid_request|"type":"error"/i.test(message)?'Model provider unavailable or malformed response':/RPC|chain|network|deployment|Market|confirm|Transaction|balance|fund/i.test(message)?'Chain operation pending or unavailable; no outcome inferred':message.slice(0,200);const final=job.attempts>=5;await finishJob(job.id,owner,final?safe+' (gave up after '+job.attempts+' attempts)':safe,final);if(final&&job.kind==='purchase'){await sql()`UPDATE market_orders SET status='FundingFailed' WHERE id=${job.payload.orderId} AND funding_tx IS NULL`.catch(()=>{})}if(job.kind==='buyer'){await sql()`UPDATE missions SET status='blocked' WHERE id=${job.payload.missionId} AND status NOT IN ('completed','stopped')`;await activity(job.payload.missionId,'system','blocked',safe)}console.error(job.kind+': '+safe)}finally{clearInterval(renew)}}await closeDatabase();
