import { canonicalJson, scopeSchema, type Capability, type EventProperty, type Metric, type ReportCore, type ReportScope, type Snapshot, type TemplateId } from '../../domain/src/index';
import { getEvent, getSportPack } from '../../sports/src/index';
import { reconcileSnapshot } from '../../sports/src/imports';
export const MIN_COHORT=20;
const required:Record<TemplateId,Capability[]>={ticket_usage_v1:['entitlements','gate_scans'],returning_buyers_v1:['account_history'],buyer_geography_v1:['account_geography'],court_session_usage_v1:['entitlements','gate_scans'],court_access_usage_v1:['court_access'],fixture_usage_v1:['fixtures','gate_scans'],ticket_product_usage_v1:['products','gate_scans'],arrival_window_v1:['arrival_times'],participant_turnout_v1:['entries','pickups','timing'],participant_return_v1:['participant_history'],day_pass_usage_v1:['days','gate_scans'],hospitality_access_v1:['hospitality'],activation_zone_usage_v1:['activation'],session_package_fit_v1:[]};
export function availableTemplates(event:EventProperty){return getSportPack(event.sportId).templates.filter(t=>required[t].every(c=>event.capabilities.includes(c)))}
export function quoteRequest(event:EventProperty,input:unknown){const parsed=scopeSchema.safeParse(input);if(!parsed.success)return {status:'not_answerable' as const,reason:'Request is outside the approved typed scope.'};const scope=parsed.data;if(scope.eventId!==event.id||!availableTemplates(event).includes(scope.templateId))return {status:'not_answerable' as const,reason:'This format/source cannot answer that measurement.'};const blocks=event.blocks.filter(b=>b.editionId===scope.editionId);if(!event.editions.some(e=>e.id===scope.editionId&&e.completed))return {status:'not_answerable' as const,reason:'Only completed disclosed editions are eligible.'};if(scope.blockIds&&(new Set(scope.blockIds).size!==scope.blockIds.length||scope.blockIds.some(id=>!blocks.some(b=>b.id===id))||(scope.blockIds.length!==1&&scope.blockIds.length!==blocks.length)))return {status:'needs_scope_adjustment' as const,reason:'Use one whole native block or the entire edition; arbitrary overlapping subsets are unavailable.'};if(scope.zoneId&&!event.zones.some(z=>z.id===scope.zoneId))return {status:'not_answerable' as const,reason:'Unknown native zone.'};if(['hospitality_access_v1','activation_zone_usage_v1','court_access_usage_v1'].includes(scope.templateId)&&!scope.zoneId)return {status:'needs_scope_adjustment' as const,reason:'Select one permitted measured zone.'};if(scope.zoneId){const zone=event.zones.find(z=>z.id===scope.zoneId)!;if(scope.templateId==='hospitality_access_v1'&&zone.kind!=='hospitality'||scope.templateId==='court_access_usage_v1'&&zone.kind!=='court'||scope.templateId==='activation_zone_usage_v1'&&!['activation','expo','finish'].includes(zone.kind))return {status:'not_answerable' as const,reason:'Selected zone does not have the required evidence semantics.'}}
if(['returning_buyers_v1','buyer_geography_v1','participant_return_v1'].includes(scope.templateId)&&(scope.blockIds||scope.category||scope.product||scope.zoneId))return {status:'needs_scope_adjustment' as const,reason:'This history template uses the complete edition population; block and access filters are unsupported.'};if(['participant_turnout_v1','activation_zone_usage_v1'].includes(scope.templateId)&&(scope.category||scope.product||scope.targetRegion))return {status:'not_answerable' as const,reason:'Ticket or geography filters do not apply to this evidence population.'};if(scope.priorEditionId&&!event.editions.some(e=>e.completed&&e.id===scope.priorEditionId&&e.id<scope.editionId))return {status:'not_answerable' as const,reason:'Prior period must be a comparable completed edition.'};return {status:'quoted' as const,reason:'Approved fixed scope; price is independent of findings.',priceWei:String(50000000000000n+BigInt(scope.blockIds?.length??blocks.length)*10000000000000n),scope};}
/** Ledger must be persisted and checked under the sponsor organization lock, not wallet scope. */
export function authorizeRelease(scope:ReportScope,prior:ReportScope[]){for(const p of prior){if(p.eventId!==scope.eventId||p.editionId!==scope.editionId)continue;if(canonicalJson(p)===canonicalJson(scope))return true;
 const history=(t:TemplateId)=>['returning_buyers_v1','buyer_geography_v1','participant_return_v1'].includes(t);
 if(history(p.templateId)||history(scope.templateId)){if(p.templateId!==scope.templateId)continue;}
 const independentZones=['hospitality_access_v1','activation_zone_usage_v1','court_access_usage_v1'];
 if(p.zoneId!==scope.zoneId&&(independentZones.includes(p.templateId)||independentZones.includes(scope.templateId)))continue;
 const filters=(s:ReportScope)=>canonicalJson({category:s.category,product:s.product,targetRegion:s.targetRegion});if(filters(p)!==filters(scope))throw new Error('Overlapping cohort refinements unavailable for this sponsor release family');}return true}

function definition(scope:ReportScope,id:string,population:string,unit:string,source:string,denominatorPolicy:string){return {id,version:'1' as const,population,unit,numeratorPolicy:'Eligible accepted observations only; deduplicate declared subject/scope',denominatorPolicy,deduplicationScope:source==='activation'?'token/zone/day':population==='purchasing accounts'?'organizer-local account/edition':'subject/native block',period:scope.editionId,geographyBasis:population==='purchasing accounts'?'coarse account geography':'not inferred',accessScope:scope.zoneId??'declared admission block',evidenceSource:source,coverage:'Only complete disclosed intervals support complete rates',suppressionPolicy:'20 protected units; suppress entire related result group if any cell is small'};}
export function computeReport(snapshot:Snapshot,input:ReportScope):ReportCore{return calculate(snapshot,input,false)}
function calculate(s:Snapshot,input:ReportScope,independent:boolean):ReportCore {
 const scope=scopeSchema.parse(input),event=getEvent(scope.eventId),quote=quoteRequest(event,scope);if(quote.status!=='quoted')throw new Error(quote.reason);if(s.eventId!==scope.eventId||s.organizerId!==event.organizerId)throw new Error('Tenant or snapshot mismatch');if(!reconcileSnapshot(s).valid)throw new Error('Frozen snapshot relationships are invalid');
 // Independent verifier path uses sorted distinct arrays instead of seller Set aggregation.
 const unique=(values:string[])=>independent?values.sort().filter((v,i,a)=>i===0||v!==a[i-1]):[...new Set(values)];const count=(values:string[])=>unique(values).length;
 const blocks=s.blocks.filter(b=>b.editionId===scope.editionId&&(!scope.blockIds||scope.blockIds.includes(b.id)));const ids=blocks.map(b=>b.id);const metrics:Metric[]=[];const protectedSizes:number[]=[];
 const coverage=s.coverage.filter(c=>ids.includes(c.blockId)&&(!scope.zoneId||!c.zoneId||c.zoneId===scope.zoneId));
 const status=(block:string,source:Snapshot['coverage'][number]['source'],zone?:string)=>s.coverage.find(c=>c.blockId===block&&c.source===source&&c.zoneId===zone)?.status??'not_collected';
 function add(id:string,label:string,n:number,d:number|undefined,protectedCount:number,population:string,unit:string,source:string,blockId?:string,zoneId?:string,state:Metric['status']='verified_purchased') {const measured=state==='verified_purchased';metrics.push({id,label,status:state,...(measured?{numerator:n,...(d!==undefined?{denominator:d,...(d>0?{value:Math.floor(n*10000/d)}:{})}:{})}:{}),unit,population,definition:definition(scope,id,population,unit,source,d===undefined?'Count only; no reach denominator':id==='geography'?'distinct accounts with known geography':id==='returning_buyers'||id==='participant_return'?'distinct qualifying current-edition population':'eligible subjects in exactly the same covered native scope'),...(blockId?{blockId}:{}),...(zoneId?{zoneId}:{}),...(scope.category?{category:scope.category}:{})});protectedSizes.push(measured?protectedCount:MIN_COHORT)}
 const accepted=s.observations.filter(o=>o.accepted&&ids.includes(o.blockId)&&blocks.some(b=>b.id===o.blockId&&b.scheduleVersion===o.scheduleVersion)&&s.coverage.some(c=>c.blockId===o.blockId&&c.source===o.kind&&(!c.zoneId||c.zoneId===o.zoneId)&&o.at>=c.from&&o.at<=c.to));
 const t=scope.templateId;
 if(t==='returning_buyers_v1'||t==='buyer_geography_v1'){
 const now=unique(s.purchases.filter(p=>p.editionId===scope.editionId&&p.status==='paid').map(p=>p.accountId));
 if(t==='returning_buyers_v1'){const prior=scope.priorEditionId??event.editions.filter(e=>e.completed&&e.id<scope.editionId).at(-1)?.id;const previous=unique(s.purchases.filter(p=>p.editionId===prior&&p.status==='paid').map(p=>p.accountId));add('returning_buyers','Returning purchasing-account share',now.filter(id=>previous.includes(id)).length,now.length,now.length,'purchasing accounts','basis_points','purchase history')}
 else{const a=s.accounts.filter(a=>now.includes(a.id)),known=a.filter(a=>a.region!==null);add('geography','Target-region share among known purchasing accounts',known.filter(a=>a.region===(scope.targetRegion??'Bay Metro')).length,known.length,known.length,'purchasing accounts','basis_points','account geography');add('unknown_geography','Unknown account geography',a.length-known.length,a.length,a.length-known.length,'purchasing accounts','basis_points','account geography')}
 }else if(t==='participant_return_v1'){
 const now=unique(s.entries.filter(e=>e.editionId===scope.editionId&&e.status==='valid').map(e=>e.participantId));const prior=scope.priorEditionId??event.editions.filter(e=>e.completed&&e.id<scope.editionId).at(-1)?.id;const past=unique(s.entries.filter(e=>e.editionId===prior&&e.status==='valid').map(e=>e.participantId));add('participant_return','Returning organizer-linked participant share',now.filter(id=>past.includes(id)).length,now.length,now.length,'organizer-local participant references','basis_points','participant history');
 }else for(const b of blocks){
 if(t==='participant_turnout_v1'||t==='session_package_fit_v1'&&event.sportId==='running'){
 const entries=s.entries.filter(e=>e.blockId===b.id&&e.status==='valid');const refs=entries.map(e=>e.id);const observed=(kind:string)=>unique(accepted.filter(o=>o.blockId===b.id&&o.kind===kind&&refs.includes(o.subjectId)).map(o=>o.subjectId));const starts=observed('start'),finishes=observed('finish');
 add('eligible_entries','Eligible participant entries',entries.length,undefined,count(entries.map(e=>e.participantId)),'participant-distance entries','entries','registrations',b.id);
 for(const kind of ['pickup','start','finish'] as const){const c=status(b.id,kind);add(kind,kind==='pickup'?'Recorded packet pickup':kind==='start'?'Observed starts':'Observed finishes',observed(kind).length,entries.length,count(entries.map(e=>e.participantId)),'participant-distance entries','basis_points',kind,b.id,undefined,c==='not_collected'?'not_collected':c==='partial'?'insufficient_coverage':'verified_purchased')}
 add('finish_without_start','Finish observations without a matched start',finishes.filter(id=>!starts.includes(id)).length,undefined,finishes.filter(id=>!starts.includes(id)).length,'participant-distance entries','entries','finish',b.id);
 add('finish_started_cohort','Observed finishes among observed starters',finishes.filter(id=>starts.includes(id)).length,starts.length,starts.length,'observed starter entries','basis_points','start+finish',b.id);
 }else if(t==='activation_zone_usage_v1'){
 const source='activation',zone=scope.zoneId!;const tokens=accepted.filter(o=>o.blockId===b.id&&o.kind===source&&o.zoneId===zone).map(o=>o.subjectId);const c=status(b.id,source,zone);add('activation_interactions','Recorded token interactions; not impressions',count(tokens),undefined,count(tokens),'zone/day interaction tokens','interactions',source,b.id,zone,c==='complete'?'verified_purchased':c==='partial'?'insufficient_coverage':'not_collected');
 }else{
 const source=t==='hospitality_access_v1'?'hospitality':t==='court_access_usage_v1'?'court':'gate';const zoneIds=scope.zoneId?[scope.zoneId]:source==='gate'&&['basketball','football_soccer'].includes(event.sportId)?event.zones.filter(z=>z.kind==='section').map(z=>z.id):[event.zones[0]!.id];for(const zone of zoneIds){const c=status(b.id,source,source==='gate'?undefined:zone);
 const es=s.entitlements.filter(e=>e.blockId===b.id&&e.status==='valid'&&e.scheduleVersion===b.scheduleVersion&&e.zoneId===zone&&(!scope.category||e.category===scope.category)&&(!scope.product||e.product===scope.product));const refs=es.map(e=>e.id);const obs=accepted.filter(o=>o.blockId===b.id&&o.kind===source&&o.zoneId===zone&&refs.includes(o.subjectId));const used=count(obs.map(o=>o.subjectId));const state=c==='complete'?'verified_purchased':c==='partial'?'insufficient_coverage':'not_collected';
 if(t==='arrival_window_v1'){
 for(const [label,min,max] of [['120–30 minutes before',-120,-30],['30–0 minutes before',-30,0],['After scheduled start',0,300]] as const){const first=unique(obs.map(o=>o.subjectId)).map(id=>obs.filter(o=>o.subjectId===id).sort((a,b)=>a.at.localeCompare(b.at))[0]!);const n=first.filter(o=>{const m=(Date.parse(o.at)-Date.parse(b.start))/60000;return m>=min&&m<max}).length;add(`arrival_${min}`,label,n,used,count(es.map(e=>e.accountId)),'recorded used ticket-block entitlements','basis_points','first gate scan versus frozen schedule',b.id,zone,state)}
 }else if(t==='ticket_product_usage_v1'){
 for(const product of unique(es.map(e=>e.product))){const group=es.filter(e=>e.product===product);add('product_'+product,`${product} recorded ticket usage`,count(obs.filter(o=>group.some(e=>e.id===o.subjectId)).map(o=>o.subjectId)),group.length,count(group.map(e=>e.accountId)),'ticket-block entitlements','basis_points',source,b.id,zone,state)}
 }else add(source==='gate'?'ticket_usage':source+'_usage',source==='gate'?'Recorded ticket-entitlement usage':source==='court'?'Recorded court-access entitlement usage':'Recorded hospitality credential usage',used,es.length,count(es.map(e=>e.accountId)),'ticket-block entitlements','basis_points',source,b.id,zone,state);
 }
 }
 }
 // Complementary suppression: no totals, numerators or ratios from a family with a protected small cell.
 if(protectedSizes.some(n=>n>0&&n<MIN_COHORT))for(const m of metrics)if(m.status==='verified_purchased'){m.status='suppressed';delete m.numerator;delete m.denominator;delete m.value}
 return {version:'1',snapshotId:s.id,eventId:event.id,sportId:event.sportId,formatId:event.formatId,templateId:t,scope,metrics,coverage,limitations:['Synthetic historical observations; not a forecast or source-authenticity proof.','Purchasers, entitlements, participants and measured interactions are distinct populations.','Incomplete scopes are excluded from complete-rate conclusions.','No broadcast reach, demographics, sponsor impressions, sales or ROI are inferred.','Suppression is a prototype control, not a formal anonymity guarantee.']};
}
export function verifyReport(snapshot:Snapshot,scope:ReportScope,core:ReportCore){try{const expected=calculate(snapshot,scope,true);const valid=canonicalJson(expected)===canonicalJson(core);return {valid,checks:[valid?'independent_recomputation_matches':'incorrect_calculation_or_semantics',...(valid?['scope_matches','disclosure_matches']:[])]}}catch{return {valid:false,checks:['invalid_scope_or_snapshot']}}}
export function compareMetrics(a:Metric,b:Metric){const keys=['population','unit','denominatorPolicy','deduplicationScope','geographyBasis','accessScope','evidenceSource'] as const;const differences=keys.filter(k=>a.definition[k]!==b.definition[k]);if(a.status!=='verified_purchased'||b.status!=='verified_purchased')return {comparable:false,mode:'not_comparable',reason:'Both criteria require verified purchased evidence.'};return {comparable:differences.length===0,mode:differences.length?'goal_level_tradeoff':'like_for_like',reason:differences.length?'Different '+differences.join(', '):'Matching population and measurement definitions; inspect period and coverage.'}}
export function rankCandidates(candidates:{eventId:string;criteria:Record<string,number|null>}[],weights:Record<string,number>){const total=Object.values(weights).reduce((a,b)=>a+b,0);if(total<=0||Object.values(weights).some(w=>w<0))throw new Error('Invalid decision weights');return candidates.map(c=>{let lower=0,upper=0;const unknowns:string[]=[];for(const [key,weight] of Object.entries(weights)){const value=c.criteria[key];if(value===null||value===undefined){unknowns.push(key);upper+=weight}else{if(value<0||value>10000)throw new Error('Criterion must be basis points');lower+=weight*value/10000;upper+=weight*value/10000}}return {eventId:c.eventId,lower:Math.floor(lower/total*10000),upper:Math.floor(upper/total*10000),unknowns}}).sort((a,b)=>b.lower-a.lower)}
