import { describe,it,expect } from 'vitest';
import { EVENTS } from '../packages/sports/src/index';
import { generateSnapshot,LOCAL_TEST_SEED } from '../packages/fixtures/src/generate';
import { computeReport,verifyReport,availableTemplates,quoteRequest,authorizeRelease,rankCandidates,compareMetrics } from '../packages/analytics/src/index';
import { canonicalJson,type ReportScope } from '../packages/domain/src/index';
const scopeFor=(id:string,templateId:ReportScope['templateId']='ticket_usage_v1'):ReportScope=>({eventId:id,templateId,editionId:id+'-2025',blockIds:[id+'-2025-b1']});
describe('six substantive sport packs',()=>{
 for(const event of EVENTS.filter((_,i)=>i%2===0))it(event.sportId+' calculations, invalid denominator, native custom scope',()=>{
 const s=generateSnapshot(event.id,LOCAL_TEST_SEED),template=event.sportId==='running'?'participant_turnout_v1':event.sportId==='golf'?'day_pass_usage_v1':event.sportId==='tennis'?'court_session_usage_v1':event.sportId==='squash'?'court_session_usage_v1':'fixture_usage_v1';const scope=scopeFor(event.id,template);const core=computeReport(s,scope);expect(core.metrics.length).toBeGreaterThan(0);expect(verifyReport(s,scope,core).valid).toBe(true);const wrong=structuredClone(core);wrong.metrics[0]!.denominator=123456;expect(verifyReport(s,scope,wrong).valid).toBe(false);expect(quoteRequest(event,scope).status).toBe('quoted');expect(availableTemplates(event).length).toBeGreaterThan(2);
 });
 it('twelve properties and six isolated organizers',()=>{expect(EVENTS).toHaveLength(12);expect(new Set(EVENTS.map(e=>e.organizerId)).size).toBe(6)});
 it('hand-check spectator reference: 40 entitlements, 20 admissions despite duplicate scans, refunded tickets excluded',()=>{
 const e=EVENTS[0]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope=scopeFor(e.id),b=s.blocks.find(b=>b.id===scope.blockIds![0])!,zone=e.zones[0]!.id;s.entitlements=Array.from({length:42},(_,i)=>({id:'x'+i,ticketId:'t'+i,accountId:'a'+i,editionId:scope.editionId,blockId:b.id,zoneId:zone,category:'paid',product:'single',status:i<40?'valid':'refunded',scheduleVersion:1}));s.observations=Array.from({length:44},(_,i)=>({id:'o'+i,subjectId:'x'+(i%22),blockId:b.id,zoneId:zone,kind:'gate',at:b.start,accepted:true,scheduleVersion:1}));s.observations=s.observations.filter(o=>!['x20','x21'].includes(o.subjectId));const m=computeReport(s,scope).metrics[0]!;expect(m.numerator).toBe(20);expect(m.denominator).toBe(40);expect(m.value).toBe(5000);
 });
 it('hand-check running intersections are not a nested funnel',()=>{const e=EVENTS[8]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope=scopeFor(e.id,'participant_turnout_v1'),b=s.blocks.find(b=>b.id===scope.blockIds![0])!;s.entries=Array.from({length:80},(_,i)=>({id:'r'+i,participantId:'p'+i,accountId:'a'+i,editionId:scope.editionId,blockId:b.id,status:'valid',version:1,bib:String(i)}));s.observations=[];for(let i=0;i<80;i++){for(const kind of ['pickup','start','finish'] as const)if(kind==='pickup'?i<60:kind==='start'?i<40:i>=20&&i<70)s.observations.push({id:kind+i,subjectId:'r'+i,blockId:b.id,zoneId:e.zones[0]!.id,kind,at:b.start,accepted:true,scheduleVersion:1})}const ms=computeReport(s,scope).metrics;expect(ms.find(m=>m.id==='pickup')?.numerator).toBe(60);expect(ms.find(m=>m.id==='start')?.numerator).toBe(40);expect(ms.find(m=>m.id==='finish')?.numerator).toBe(50);expect(ms.find(m=>m.id==='finish_without_start')?.numerator).toBe(30);expect(ms.find(m=>m.id==='finish_started_cohort')?.numerator).toBe(20)});
 it('outages stay unknown and nested tennis entitlements never inflate grounds entry',()=>{const e=EVENTS[2]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED);const scope=scopeFor(e.id);scope.blockIds=[e.id+'-2025-b2'];expect(computeReport(s,scope).metrics[0]!.status).toBe('insufficient_coverage');const whole=computeReport(s,scopeFor(e.id));const b=e.id+'-2025-b1';expect(whole.metrics[0]!.denominator).toBe(s.entitlements.filter(x=>x.blockId===b&&x.zoneId===e.zones[0]!.id&&x.status==='valid').length)});
 it('source capability rejects participant-as-spectator substitution and uncollected golf zone',()=>{const running=EVENTS[8]!,golf=EVENTS[11]!;expect(quoteRequest(running,scopeFor(running.id)).status).toBe('not_answerable');expect(quoteRequest(golf,{...scopeFor(golf.id,'hospitality_access_v1'),zoneId:golf.zones[1]!.id}).status).toBe('not_answerable')});
 it('protected small cohorts suppress complementary totals without exposing ratios',()=>{const e=EVENTS[0]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED);s.entitlements=s.entitlements.map(t=>({...t,accountId:'a0'}));const core=computeReport(s,scopeFor(e.id));expect(core.metrics[0]!.status).toBe('suppressed');expect(core.metrics[0]!.numerator).toBeUndefined();expect(core.metrics[0]!.denominator).toBeUndefined()});
 it('strict scopes and release ledger reject overlapping refinements',()=>{const e=EVENTS[0]!,scope=scopeFor(e.id);expect(quoteRequest(e,{...scope,sql:'select *'}).status).toBe('not_answerable');expect(quoteRequest(e,{...scope,blockIds:[e.id+'-2025-b1',e.id+'-2025-b2']}).status).toBe('needs_scope_adjustment');expect(()=>authorizeRelease({...scope,category:'paid'},[scope])).toThrow();expect(authorizeRelease(scope,[scope])).toBe(true)});
 it('rank bounds preserve unknowns; changing purchased inputs changes winner',()=>{const a={eventId:'a',criteria:{fit:8000}},b={eventId:'b',criteria:{fit:9000}};expect(rankCandidates([a,b],{fit:1})[0]!.eventId).toBe('b');expect(rankCandidates([{...a,criteria:{fit:10000}},b],{fit:1})[0]!.eventId).toBe('a');expect(rankCandidates([{eventId:'u',criteria:{fit:null}}],{fit:1})[0]).toMatchObject({lower:0,upper:10000,unknowns:['fit']})});
 it('same percentages cannot equate incompatible populations; canonical core rejects fractions',()=>{const a=computeReport(generateSnapshot(EVENTS[0]!.id,LOCAL_TEST_SEED),scopeFor(EVENTS[0]!.id)).metrics[0]!,b=structuredClone(a);b.definition.population='participant entries';expect(compareMetrics(a,b).comparable).toBe(false);expect(()=>canonicalJson({value:.5})).toThrow()});
 it('snapshot changes alter recomputation; frozen results are immutable to pack updates',()=>{const e=EVENTS[0]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope=scopeFor(e.id),core=computeReport(s,scope);const before=canonicalJson(core);s.observations=[];expect(verifyReport(s,scope,core).valid).toBe(false);expect(canonicalJson(core)).toBe(before)});
});

describe('source adapter validation and return denominators',()=>{
 it('returning buyer share divides by current buyers, not prior buyers or ticket count',()=>{const e=EVENTS[0]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED);s.purchases=[];for(let i=0;i<80;i++)s.purchases.push({id:'old'+i,accountId:'a'+i,editionId:e.id+'-2024',status:'paid'});for(let i=40;i<100;i++)s.purchases.push({id:'new'+i,accountId:'a'+i,editionId:e.id+'-2025',status:'paid'});s.purchases.push({id:'duplicate',accountId:'a45',editionId:e.id+'-2025',status:'paid'});const m=computeReport(s,{eventId:e.id,editionId:e.id+'-2025',templateId:'returning_buyers_v1'}).metrics[0]!;expect(m.numerator).toBe(40);expect(m.denominator).toBe(60)});
 it('golf grounds and club scopes differ and basketball transfer does not inflate supply',()=>{for(const id of [EVENTS[4]!.id,EVENTS[10]!.id]){const s=generateSnapshot(id,LOCAL_TEST_SEED),scope=scopeFor(id),before=computeReport(s,scope);s.transfers.push({id:'another-transfer',ticketId:s.entitlements[0]!.ticketId,from:'a',to:'b'});expect(computeReport(s,scope)).toEqual(before)}});
 it('soccer stale schedule scans are excluded',()=>{const e=EVENTS[6]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope=scopeFor(e.id);const core=computeReport(s,scope);for(const o of s.observations)o.scheduleVersion=0;expect(computeReport(s,scope).metrics[0]!.numerator).toBe(0);expect(verifyReport(s,scope,core).valid).toBe(false)});
 it('activation tokens deduplicate repeated scans and unavailable zones stay unknown',()=>{const e=EVENTS[8]!,s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope={...scopeFor(e.id,'activation_zone_usage_v1'),zoneId:e.zones[0]!.id};const before=computeReport(s,scope);s.observations.push(...s.observations.filter(o=>o.kind==='activation').map(o=>({...o,id:o.id+'duplicate'})));expect(computeReport(s,scope)).toEqual(before)});
});

import { VersionedPackRegistry } from '../packages/sports/src/versioned-registry';
import { validateImport,reconcileSnapshot } from '../packages/sports/src/imports';
it('reviewed developer extension installs without escrow or delivery changes and preserves older version',()=>{const registry=new VersionedPackRegistry();registry.register({id:'cycling_test',version:'1',formats:['closed_circuit_test'],templates:['ticket_usage_v1'],nativeView:'circuit-test'});const original=registry.resolve('cycling_test','1');registry.register({id:'cycling_test',version:'2',formats:['closed_circuit_test'],templates:['ticket_usage_v1','arrival_window_v1'],nativeView:'circuit-v2-test'});expect(registry.resolve('cycling_test','1')).toEqual(original);expect(()=>registry.register({...original})).toThrow();expect(()=>registry.resolve('not_reviewed','1')).toThrow()});
it('generated source relationships reconcile and wrong tenant/import tables fail',()=>{for(const event of EVENTS){expect(reconcileSnapshot(generateSnapshot(event.id,LOCAL_TEST_SEED)).valid).toBe(true)}expect(()=>validateImport(EVENTS[8]!,'entitlements',[])).toThrow();expect(()=>validateImport(EVENTS[0]!,'accounts',[{id:'a',organizerId:'foreign',region:null}])).toThrow()});

import { selectEvidence } from '../packages/domain/src/evidence-selection';
it('upcoming inventory is actually future relative to demo date, and tennis has concurrent court sessions',()=>{for(const e of EVENTS){for(const edition of e.editions.filter(x=>!x.completed)){expect(e.blocks.filter(b=>b.editionId===edition.id).every(b=>Date.parse(b.start)>Date.parse('2026-09-10'))).toBe(true)}}const tennis=EVENTS[2]!,blocks=tennis.blocks.filter(b=>b.editionId.endsWith('2025'));expect(blocks).toHaveLength(4);expect(blocks[0]!.start).toBe(blocks[1]!.start);expect(blocks[0]!.court).not.toBe(blocks[1]!.court)});
it('native UI matching does not relabel a paid category report as all/complimentary or a different edition',()=>{const event=EVENTS[0]!,scope={...scopeFor(event.id),category:'paid' as const},core=computeReport(generateSnapshot(event.id,LOCAL_TEST_SEED),scope),selection={eventId:event.id,editionId:scope.editionId,blockId:scope.blockIds![0]!,zoneId:event.zones[0]!.id};expect(selectEvidence([core],selection).metrics).toHaveLength(0);expect(selectEvidence([core],{...selection,category:'complimentary'}).metrics).toHaveLength(0);expect(selectEvidence([core],{...selection,category:'paid'}).metrics.length).toBeGreaterThan(0);expect(selectEvidence([core],{...selection,category:'paid',editionId:event.id+'-2024'}).metrics).toHaveLength(0)});

import { parseImportCsv } from '../packages/sports/src/imports';
it('organizer CSV parser validates quoted fields, strict columns, tenant and file bounds',()=>{const e=EVENTS[0]!;const parsed=parseImportCsv(e,'accounts',`id,organizerId,region\na1,${e.organizerId},"Bay Metro"\na2,${e.organizerId},\n`);expect(parsed.rows).toHaveLength(2);expect(parsed.rows[1]).toHaveProperty('region',null);expect(()=>parseImportCsv(e,'accounts','id,id\na,b')).toThrow();expect(()=>parseImportCsv(e,'accounts','id,organizerId,region\na,other,Bay Metro')).toThrow();expect(()=>parseImportCsv(e,'accounts','id,organizerId,region,sql\na,b,,x')).toThrow();expect(()=>parseImportCsv(e,'accounts','x'.repeat(2_000_001))).toThrow()});
it('native custom follow-up may purchase distinct instrumented zone while cohort differencing stays blocked',()=>{const event=EVENTS[0]!,prior=scopeFor(event.id),next={...prior,templateId:'hospitality_access_v1' as const,zoneId:event.zones[2]!.id};expect(authorizeRelease(next,[prior])).toBe(true);expect(()=>authorizeRelease({...prior,category:'paid'},[prior])).toThrow()});
it('basketball and soccer maps have real assigned-section cohorts with arrival-window evidence',()=>{for(const e of [EVENTS[4]!,EVENTS[6]!]){const s=generateSnapshot(e.id,LOCAL_TEST_SEED),scope=scopeFor(e.id,'fixture_usage_v1'),core=computeReport(s,scope);expect(new Set(core.metrics.map(m=>m.zoneId)).size).toBe(2);for(const m of core.metrics)expect(m.denominator).toBeGreaterThan(20);const arrivals=computeReport(s,{...scope,templateId:'arrival_window_v1'});expect(arrivals.metrics).toHaveLength(6);expect(arrivals.metrics.every(m=>m.definition.evidenceSource==='first gate scan versus frozen schedule')).toBe(true)}});
