import {describe,it,expect} from 'vitest';
import {synchronizeHistory,summarizeSellerHistory,type IndexedEvent,type HistorySource,type HistoryStore,type Checkpoint} from '../packages/server/history';
const tx=(n:number)=>'0x'+n.toString(16).padStart(64,'0');
function event(n:number,name:string,args:Record<string,unknown>,canonical=true):IndexedEvent{return {transactionHash:tx(n),logIndex:0,blockNumber:BigInt(n),blockHash:'block-'+n,timestamp:BigInt(n*10),eventName:name,args,canonical};}
class MemoryStore implements HistoryStore {
 next=1n;events:IndexedEvent[]=[];points:Checkpoint[]=[];rollbacks:bigint[]=[];
 async cursor(){return this.next;}async checkpoints(){return this.points;}
 async rollback(from:bigint){this.rollbacks.push(from);for(const e of this.events)if(e.blockNumber>=from)e.canonical=false;this.points=this.points.filter(p=>p.number<from);this.next=from;}
 async append(events:IndexedEvent[],point:Checkpoint,next:bigint){for(const e of events){const i=this.events.findIndex(x=>x.transactionHash===e.transactionHash&&x.logIndex===e.logIndex);if(i<0)this.events.push(e);else this.events[i]=e;}this.points.push(point);this.next=next;}
}
function source(events:IndexedEvent[],head=10n,changed=new Map<bigint,string>()):HistorySource{return {sealedHead:async()=>head,block:async n=>({hash:changed.get(n)??'block-'+n,timestamp:n*10n}),events:async(from,to)=>events.filter(e=>e.blockNumber>=from&&e.blockNumber<=to).map(e=>({...e,blockHash:changed.get(e.blockNumber)??e.blockHash}))};}
const seller='0x1111111111111111111111111111111111111111';
const stream=[event(1,'OfferRegistered',{offerId:'1',seller}),event(2,'Purchased',{offerId:'1',orderId:'1'}),event(3,'Delivered',{orderId:'1'}),event(4,'Outcome',{orderId:'1',status:4,reason:0,amount:'100',buyerAccepted:true}),event(5,'Purchased',{offerId:'1',orderId:'2'}),event(6,'Outcome',{orderId:'2',status:5,reason:2,amount:'100',buyerAccepted:false}),event(7,'Withdrawn',{account:seller,amount:'100'})];
describe('durable confirmed event indexing',()=>{
 it('indexes only two-confirmation depth and retries without duplicates',async()=>{const store=new MemoryStore();await synchronizeHistory(store,source(stream,7n),1n);expect(store.next).toBe(7n);expect(store.events).toHaveLength(6);await synchronizeHistory(store,source(stream,7n),1n);expect(store.events).toHaveLength(6);await synchronizeHistory(store,source(stream,8n),1n);expect(store.events).toHaveLength(7);});
 it('rebuild produces identical factual counts',async()=>{const first=new MemoryStore(),rebuilt=new MemoryStore();await synchronizeHistory(first,source(stream),1n,2,3n);await synchronizeHistory(first,source(stream),1n,2,3n);await synchronizeHistory(first,source(stream),1n,2,3n);await synchronizeHistory(rebuilt,source(stream),1n);expect(summarizeSellerHistory(first.events,[],{seller})).toEqual(summarizeSellerHistory(rebuilt.events,[],{seller}));});
 it('reorg invalidates old branch and resumes from surviving checkpoint',async()=>{const store=new MemoryStore();await synchronizeHistory(store,source(stream),1n,2,3n);await synchronizeHistory(store,source(stream),1n,2,3n);const changed=new Map([[6n,'replacement-6']]);await synchronizeHistory(store,source(stream.filter(e=>e.blockNumber<4n),10n,changed),1n,2,3n);expect(store.rollbacks).toEqual([4n]);expect(store.events.filter(e=>e.canonical).map(e=>e.eventName)).not.toContain('Outcome');const history=summarizeSellerHistory(store.events,[],{seller});expect(history.settled).toBe(0);expect(history.objectivelyInvalid).toBe(0);});
 it('RPC failure never advances durable cursor',async()=>{const store=new MemoryStore();const rpc=source(stream);rpc.events=async()=>{throw new Error('RPC unavailable')};await expect(synchronizeHistory(store,rpc,1n)).rejects.toThrow();expect(store.next).toBe(1n);expect(store.events).toHaveLength(0);});
 it('rejects a reorganization during range scan',async()=>{const store=new MemoryStore();const rpc=source(stream);let calls=0;rpc.block=async n=>({hash:n===9n&&++calls>1?'new-fork':'block-'+n,timestamp:n*10n});await expect(synchronizeHistory(store,rpc,1n)).rejects.toThrow('Reorganization');expect(store.next).toBe(1n);});
});
describe('factual seller outcomes',()=>{
 it('valid unfavorable findings paid, invalid refunded, scoped withdrawal unavailable',()=>{const h=summarizeSellerHistory(stream,[{chainOfferId:'1',sportId:'squash',templateId:'ticket_usage_v1'}],{seller,sportId:'squash'});expect(h.settled).toBe(1);expect(h.buyerAccepted).toBe(1);expect(h.objectivelyInvalid).toBe(1);expect(h.verifierTimeouts).toBe(0);expect(h.medianDeliverySeconds).toBe(10);expect(h.withdrawnWei).toBeNull();expect(h.settledWei).toBe('100');});
 it('does not invent cross-sport reputation or treat service timeouts as fraud',()=>{const events=[...stream,event(8,'Purchased',{offerId:'1',orderId:'3'}),event(9,'Disputed',{orderId:'3'}),event(10,'Outcome',{orderId:'3',status:5,reason:9,amount:'100'})];const h=summarizeSellerHistory(events,[],{seller});expect(h.verifierTimeouts).toBe(1);expect(h.objectivelyInvalid).toBe(1);expect(h.disputeRefunded).toBe(1);expect(summarizeSellerHistory(events,[{chainOfferId:'1',sportId:'squash',templateId:'ticket_usage_v1'}],{sportId:'running'}).purchases).toBe(0);});
 it('empty history stays zero with no fabricated outcomes',()=>{expect(summarizeSellerHistory([],[]).outcomes).toEqual([]);expect(summarizeSellerHistory([],[]).medianDeliverySeconds).toBeNull();});
});
