import { z } from 'zod';
export const sportIds = ['squash','tennis','basketball','football_soccer','running','golf'] as const;
export type SportId = typeof sportIds[number];
export const templateIds = ['ticket_usage_v1','returning_buyers_v1','buyer_geography_v1','court_session_usage_v1','court_access_usage_v1','fixture_usage_v1','ticket_product_usage_v1','arrival_window_v1','participant_turnout_v1','participant_return_v1','day_pass_usage_v1','hospitality_access_v1','activation_zone_usage_v1','session_package_fit_v1'] as const;
export type TemplateId = typeof templateIds[number];
export type EvidenceStatus = 'available_unpurchased'|'verified_purchased'|'organizer_claim'|'not_collected'|'not_applicable'|'insufficient_coverage'|'suppressed'|'not_comparable';
export type Capability = 'entitlements'|'gate_scans'|'account_history'|'account_geography'|'court_access'|'fixtures'|'products'|'arrival_times'|'entries'|'pickups'|'timing'|'participant_history'|'days'|'hospitality'|'activation';
export const scopeSchema = z.object({eventId:z.string().min(1),templateId:z.enum(templateIds),editionId:z.string().min(1),blockIds:z.array(z.string()).min(1).max(8).optional(),zoneId:z.string().optional(),category:z.enum(['paid','complimentary','hospitality']).optional(),product:z.enum(['single','series','group','complimentary','grounds','weekly']).optional(),targetRegion:z.enum(['Bay Metro','North Coast','Inland']).optional(),priorEditionId:z.string().optional()}).strict();
export type ReportScope = z.infer<typeof scopeSchema>;
export interface NativeBlock {id:string;label:string;kind:'session'|'fixture'|'race'|'day';start:string;end:string;scheduleVersion:number;editionId:string;round?:string;court?:string;opponent?:string;distance?:string;wave?:string;rescheduled?:boolean}
export interface Zone {id:string;label:string;kind:'court'|'section'|'grounds'|'hospitality'|'activation'|'expo'|'finish';x:number;y:number;instrumented:boolean;accessRule:string}
export interface SponsorshipPackage {id:string;name:string;priceCents:number;activation:'hospitality'|'demonstration'|'participant_sampling';blockIds:string[];zoneIds:string[];rights:string[];restrictions:string[];available:boolean;editionId:string}
export interface EventProperty {id:string;name:string;sportId:SportId;formatId:string;formatVersion:'1';organizerId:string;organizerName:string;location:string;description:string;synthetic:true;capabilities:Capability[];editions:{id:string;year:number;completed:boolean}[];blocks:NativeBlock[];zones:Zone[];packages:SponsorshipPackage[];coverageDisclosure:string;customQuestion:string}
export interface MetricDefinition {id:string;version:'1';population:string;unit:string;numeratorPolicy:string;denominatorPolicy:string;deduplicationScope:string;period:string;geographyBasis:string;accessScope:string;evidenceSource:string;coverage:string;suppressionPolicy:string}
export interface Metric {id:string;label:string;status:EvidenceStatus;numerator?:number;denominator?:number;value?:number;unit:string;population:string;definition:MetricDefinition;blockId?:string;zoneId?:string;category?:string}
export interface Coverage {blockId:string;source:'gate'|'court'|'hospitality'|'activation'|'pickup'|'start'|'finish';zoneId?:string;status:'complete'|'partial'|'not_collected';from:string;to:string;reason?:string}
export interface ReportCore {version:'1';snapshotId:string;eventId:string;sportId:SportId;formatId:string;templateId:TemplateId;scope:ReportScope;metrics:Metric[];coverage:Coverage[];limitations:string[]}
export interface Account {id:string;organizerId:string;region:string|null}
export interface Purchase {id:string;accountId:string;editionId:string;status:'paid'|'refunded'}
export interface Entitlement {id:string;ticketId:string;accountId:string;editionId:string;blockId:string;zoneId:string;category:'paid'|'complimentary'|'hospitality';product:string;status:'valid'|'refunded'|'void';scheduleVersion:number}
export interface Observation {id:string;subjectId:string;blockId:string;zoneId:string;kind:'gate'|'court'|'hospitality'|'activation'|'pickup'|'start'|'finish';at:string;accepted:boolean;scheduleVersion:number}
export interface ParticipantEntry {id:string;participantId:string;accountId:string;editionId:string;blockId:string;status:'valid'|'cancelled'|'transferred';version:number;bib:string}
export interface Snapshot {id:string;eventId:string;organizerId:string;normalizationVersion:'1';policyVersion:'1';synthetic:true;accounts:Account[];purchases:Purchase[];entitlements:Entitlement[];observations:Observation[];coverage:Coverage[];entries:ParticipantEntry[];transfers:{id:string;ticketId?:string;entryId?:string;from:string;to:string}[];blocks:NativeBlock[];zones:Zone[]}
export function canonicalJson(value:unknown):string { if(value===null||typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'){if(!Number.isSafeInteger(value))throw new Error('Canonical values require safe integers; represent ratios as numerator/denominator');return String(value)}if(Array.isArray(value))return '['+value.map(canonicalJson).join(',')+']';if(typeof value==='object')return '{'+Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b,'en')).map(([k,v])=>JSON.stringify(k)+':'+canonicalJson(v)).join(',')+'}';throw new Error('Unsupported canonical value') }
