import {encrypt,decrypt} from '../server/crypto';
import {z} from 'zod';
import {sql,enqueue} from '../database/index';
import {EVENTS,SPORT_PACKS} from '../sports/src/index';
import {availableTemplates,rankCandidates} from '../analytics/src/index';
import {scopeSchema} from '../domain/src/index';
import {getMission,listPublicOffers,activity,type Principal} from '../server/index';
import {purchaseOffer,readReport,acceptOrder,disputeOrder,customRequest,prepareOffer} from '../server/market';
import {buyerInstructions,sellerInstructions,modelStep,type AgentTool} from './provider';
const string={type:'string'};
function tool(name:string,description:string,properties:Record<string,unknown>,schema:z.ZodType,execute:AgentTool['execute']):AgentTool{return {name,description,parameters:{type:'object',properties,required:Object.keys(properties),additionalProperties:false},schema,execute}}
export async function runBuyer(missionId:string){const [m]=await sql()`SELECT * FROM missions WHERE id=${missionId}`;if(!m||['stopped','completed','failed'].includes(m.status))return;const principal:Principal={id:m.principal_id,tenantId:m.tenant_id,role:'buyer'};const credentials=m.provider_credentials?decrypt<{apiKey:string;model:string}>(m.provider_credentials,'mission:'+missionId,'AGENT_KEY_ENCRYPTION_KEY'):undefined;const {platformCredentials}=await import('./provider');if(!credentials&&(process.env.FORCE_BYOK==='true'||!platformCredentials()))throw new Error('Live provider configuration missing: mission has no key and the server has none');if(m.steps>=Math.min(30,Number(process.env.MAX_AGENT_STEPS??30))){await sql()`UPDATE missions SET status='completed',provider_credentials=NULL,state=state||'{"abstention":"Bounded model step limit reached"}'::jsonb WHERE id=${missionId}`;return}const mission=await getMission(principal,missionId),offers=await listPublicOffers(principal);const events=EVENTS.filter(e=>m.sports.includes(e.sportId));const tools:AgentTool[]=[
 tool('decline_offer','Record why evidence is unsuitable without purchasing it.',{offerId:string,reason:string},z.object({offerId:z.string(),reason:z.string().min(5).max(1500)}).strict(),async a=>{if(!offers.some(o=>o.id===a.offerId))throw new Error('Offer not visible');await activity(missionId,'buyer','declined',a.reason,{offerId:a.offerId});return {declined:a.offerId}}),
 tool('purchase_offer','Reserve budget and enqueue a real chain purchase.',{offerId:string,rationale:string},z.object({offerId:z.string(),rationale:z.string().min(5).max(1500)}).strict(),async a=>{const result=await purchaseOffer(principal,missionId,a.offerId);await activity(missionId,'buyer','purchase_requested',a.rationale,{offerId:a.offerId});return result}),
 tool('read_purchased_report','Read only this sponsor’s canonically confirmed delivery.',{orderId:string},z.object({orderId:z.string()}).strict(),async a=>{const result=await readReport(principal,a.orderId);return result}),
 tool('accept_delivery','Pay for objectively correct delivered evidence even when commercially unfavorable.',{orderId:string},z.object({orderId:z.string()}).strict(),async a=>acceptOrder(principal,a.orderId)),
 tool('open_dispute','Challenge only an objective defect; unfavorable findings are never a valid reason.',{orderId:string,reason:{type:'integer',description:'Objective defect code, 1 through 7'}},z.object({orderId:z.string(),reason:z.number().int().min(1).max(7)}).strict(),async a=>disputeOrder(principal,a.orderId,a.reason)),
 tool('request_custom_analysis','Ask bounded sport-native follow-up. Scope must be an approved template with the event’s actual capabilities.',{eventId:string,templateId:string,editionId:string,question:string,zoneId:{type:['string','null']},blockId:{type:['string','null']}},z.object({eventId:z.string(),templateId:z.string(),editionId:z.string(),question:z.string().max(2000),zoneId:z.string().nullable(),blockId:z.string().nullable()}).strict(),async a=>customRequest(principal,{missionId,question:a.question,scope:scopeSchema.parse({eventId:a.eventId,templateId:a.templateId,editionId:a.editionId,...(a.zoneId?{zoneId:a.zoneId}:{}),...(a.blockId?{blockIds:[a.blockId]}:{})})})),
 tool('wait_for_delivery','Wait for durable chain jobs without spending or inventing outcomes.',{reason:string},z.object({reason:z.string().max(400)}).strict(),async a=>({waiting:true,reason:a.reason})),
 tool('compare_candidates','Compute evidence-qualified bounds using purchased compatible evidence. Unknown is an explicit interval, never zero.',{criterion:string},z.object({criterion:z.enum(['recorded_usage','activation_interactions'])}).strict(),async a=>{const results=[];for(const event of events){let value:number|null=null;for(const o of mission.orders){try{const report=await readReport(principal,o.id);if(report.core.eventId!==event.id)continue;const metric=report.core.metrics.find(x=>x.status==='verified_purchased'&&(a.criterion==='recorded_usage'?x.id==='ticket_usage':x.id==='activation_interactions'));if(metric?.value!==undefined)value=metric.value}catch{}}results.push({eventId:event.id,criteria:{[a.criterion]:value}})}return {method:'User decision aid: equally weighted single evidence criterion, missing values bounded 0–10000; populations not pooled',ranking:rankCandidates(results,{[a.criterion]:1})}}),
 tool('finalize_recommendation','Finish with purchased evidence references; event/package must be eligible. Empty ids mean abstain.',{eventId:string,packageId:string,reason:string,evidenceOrderIds:{type:'array',items:string},unknowns:{type:'array',items:string},whatChanged:string},z.object({eventId:z.string(),packageId:z.string(),reason:z.string().max(2000),evidenceOrderIds:z.array(z.string()).max(20),unknowns:z.array(z.string()).max(20),whatChanged:z.string().max(2000)}).strict(),async a=>{if(a.eventId){const event=events.find(e=>e.id===a.eventId),pack=event?.packages.find(p=>p.id===a.packageId&&p.available&&p.priceCents<=Number(m.package_budget_cents)&&(m.objective==='hospitality'?p.activation==='hospitality':m.objective==='participant_sampling'?p.activation==='participant_sampling':p.activation==='demonstration'));if(!event||!pack||!a.evidenceOrderIds.length)throw new Error('Recommendation needs eligible package and purchased evidence');let supported=false;for(const id of a.evidenceOrderIds){const report=await readReport(principal,id);if(report.core.eventId===a.eventId)supported=true}if(!supported)throw new Error('Chosen event requires its own purchased evidence')}await sql()`UPDATE missions SET status='completed',provider_credentials=NULL,state=state||${sql().json({recommendation:a})}::jsonb,updated_at=now() WHERE id=${missionId}`;return {completed:true}})
 ];
 await sql()`UPDATE missions SET status='researching',updated_at=now() WHERE id=${missionId}`;
 // Each turn is reconstructed from this principal's public metadata and purchased cores only.
 const evidence:unknown[]=[];for(const o of mission.orders){if(['Delivered','Settled'].includes(o.status)){try{evidence.push(await readReport(principal,o.id))}catch{}}}
 const result=await modelStep(buyerInstructions,{mission:{objective:m.objective,brief:m.brief,packageBudgetCents:m.package_budget_cents,budgetWei:m.budget_wei},events,offers,orders:mission.orders,reservations:mission.reservations,activity:mission.activity,purchasedEvidence:evidence,lastToolOutput:m.state.privateToolOutput?decrypt(m.state.privateToolOutput,missionId):null},tools,missionId+':'+m.steps,credentials);
 await activity(missionId,'buyer','tool',`Executed ${result.tool}`,{tool:result.tool});await sql()`UPDATE missions SET steps=steps+1,state=state||${sql().json({lastTool:result.tool,privateToolOutput:encrypt(result.output,missionId)})}::jsonb WHERE id=${missionId}`;await enqueue(missionId+':step:'+String(m.steps+1),'buyer',{missionId},['wait_for_delivery','purchase_offer'].includes(result.tool)?30:0);}
export async function runSeller(tenantId:string){const inventory=EVENTS.filter(e=>e.organizerId===tenantId);if(!inventory.length)throw new Error('Seller tenant unavailable');const existing=await sql()`SELECT id,event_id,manifest,status FROM offers WHERE tenant_id=${tenantId} AND allowed_principal IS NULL AND status<>'cancelled'`;const native:Record<string,string[]>={squash:['court_session_usage_v1','buyer_geography_v1'],tennis:['court_session_usage_v1','court_access_usage_v1'],basketball:['fixture_usage_v1','ticket_product_usage_v1'],football_soccer:['fixture_usage_v1','arrival_window_v1'],running:['participant_turnout_v1','participant_return_v1'],golf:['day_pass_usage_v1','hospitality_access_v1']};const desired=inventory.flatMap(event=>(native[event.sportId]??availableTemplates(event).slice(0,2)).filter(t=>availableTemplates(event).includes(t as any)).map(templateId=>{const zone=templateId==='court_access_usage_v1'?event.zones.find(z=>z.kind==='court'&&z.instrumented):templateId==='hospitality_access_v1'?event.zones.find(z=>z.kind==='hospitality'&&z.instrumented):undefined;return {scopeId:event.id+':'+templateId,scope:scopeSchema.parse({eventId:event.id,templateId,editionId:event.editions.filter(e=>e.completed).at(-1)!.id,...(zone?{zoneId:zone.id}:{})})}}));const remaining=desired.filter(d=>!existing.some(o=>o.event_id===d.scope.eventId&&o.manifest.templateId===d.scope.templateId));if(!remaining.length)return {completed:true,catalogOffers:existing.length};const tools=[tool('publish_offer','Select one approved missing catalog scope. Compute and precommit; publication is seller-signed by durable jobs.',{scopeId:{type:'string',enum:remaining.map(d=>d.scopeId)}},z.object({scopeId:z.string()}).strict(),async a=>{const target=remaining.find(d=>d.scopeId===a.scopeId);if(!target)throw new Error('Scope outside organizer catalog policy');return prepareOffer(tenantId,target.scope)})];const result=await modelStep(sellerInstructions,{existingOffers:existing,authorizedInventory:inventory,missingCatalog:remaining,pricePolicy:'50000000000000 wei plus 10000000000000 per native block; no dependence on results',packs:SPORT_PACKS},tools,'seller:'+tenantId+':'+remaining.map(r=>r.scopeId).join('|'));await enqueue('seller:'+tenantId+':remaining:'+String(remaining.length-1),'seller',{tenantId});return result}
