import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
let connection: ReturnType<typeof postgres> | undefined;
export function sql(){ if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required'); return connection ??= postgres(process.env.DATABASE_URL,{max:10,connect_timeout:5,onnotice:()=>{},prepare:!process.env.DATABASE_URL.includes('-pooler')}); }
export function database(){return drizzle(sql());}
export async function closeDatabase(){if(connection){await connection.end();connection=undefined}}
export async function enqueue(id:string,kind:string,payload:Record<string,unknown>,delaySeconds=0){await sql()`INSERT INTO jobs(id,kind,payload,run_at) VALUES(${id},${kind},${sql().json(payload as any)},now()+${delaySeconds}*interval '1 second') ON CONFLICT(id) DO NOTHING`;}
export async function claimJob(owner:string,kinds?:string[]){const rows=await sql()`UPDATE jobs SET status='running',lease_owner=${owner},lease_until=now()+interval '90 seconds',attempts=attempts+1 WHERE id=(SELECT id FROM jobs WHERE ((status='queued' AND run_at<=now()) OR (status='running' AND lease_until<now())) AND (${!kinds} OR kind=ANY(${kinds??[]}::text[])) ORDER BY run_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`;return rows[0];}
export async function finishJob(id:string,owner:string,error?:string,final=false){await sql()`UPDATE jobs SET status=${error&&!final?'queued':'done'},last_error=${error??null},run_at=now()+interval '15 seconds',lease_until=NULL,lease_owner=NULL WHERE id=${id} AND lease_owner=${owner}`;}
export async function reserveBudget(missionId:string,offerId:string,priceWei:string){if(!/^\d+$/.test(priceWei)||BigInt(priceWei)<=0n)throw new Error('Invalid price');return sql().begin(async tx=>{const [mission]=await tx`SELECT * FROM missions WHERE id=${missionId} FOR UPDATE`;if(!mission||['stopped','completed','failed'].includes(mission.status))throw new Error('Mission does not authorize spending');const [existing]=await tx`SELECT * FROM budget_reservations WHERE mission_id=${missionId} AND offer_id=${offerId}`;if(existing)return existing;const [used]=await tx`SELECT COALESCE(sum(price_wei),0)::text AS wei FROM budget_reservations WHERE mission_id=${missionId} AND status IN ('reserved','spent')`;if(BigInt(used.wei)+BigInt(priceWei)>BigInt(mission.budget_wei))throw new Error('Research budget exceeded');const id=missionId+':'+offerId;const [result]=await tx`INSERT INTO budget_reservations(id,mission_id,offer_id,price_wei,status) VALUES(${id},${missionId},${offerId},${priceWei},'reserved') RETURNING *`;return result});}
