import {randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {sql,enqueue} from '../database/index';
import {tokenHash,encrypt} from './crypto';
export interface Principal{id:string;tenantId:string;role:'buyer'|'seller'|'operator'}
export async function createSession(){const id=randomUUID(),tenantId=randomUUID(),token=randomBytes(32).toString('hex');await sql().begin(async tx=>{await tx`INSERT INTO tenants(id,name,kind) VALUES(${tenantId},'Fictional sponsor workspace','sponsor')`;await tx`INSERT INTO principals(id,tenant_id,role) VALUES(${id},${tenantId},'buyer')`;await tx`INSERT INTO sessions(token_hash,principal_id,expires_at) VALUES(${tokenHash(token)},${id},now()+interval '7 days')`});return {token,principal:{id,tenantId,role:'buyer' as const}}}
export async function verifySession(token:string|undefined):Promise<Principal|null>{if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const [p]=await sql()`SELECT p.id,p.tenant_id,p.role FROM sessions s JOIN principals p ON p.id=s.principal_id WHERE s.token_hash=${tokenHash(token)} AND s.expires_at>now()`;return p?{id:p.id,tenantId:p.tenant_id,role:p.role}:null}
export const missionSchema=z.object({objective:z.enum(['hospitality','participant_sampling','local_spectator']),brief:z.string().min(12).max(3000),sports:z.array(z.enum(['squash','tennis','basketball','football_soccer','running','golf'])).min(1).max(6),packageBudgetCents:z.number().int().min(1).max(100_000_000),researchBudgetWei:z.string().regex(/^\d+$/).refine(v=>BigInt(v)>0n&&BigInt(v)<=1000000000000000n),gasBudgetWei:z.string().regex(/^\d+$/).default('1000000000000000'),providerKey:z.string().regex(/^sk-[A-Za-z0-9_-]{20,240}$/,'API keys start with sk-').optional(),providerModel:z.string().min(2).max(64).optional()}).strict();
export async function createMission(principal:Principal,input:unknown){if(principal.role!=='buyer')throw new Error('Buyer authorization required');const p=missionSchema.parse(input),id=randomUUID();const {validateProviderKey,platformCredentials,defaultModelFor}=await import('../agents/provider');if(!p.providerKey&&(process.env.FORCE_BYOK==='true'||!platformCredentials()))throw new Error('This deployment requires your own API key (Anthropic or OpenAI) to run a mission');const chosenModel=p.providerKey?(p.providerModel||defaultModelFor(p.providerKey)):undefined;if(p.providerKey)await validateProviderKey({apiKey:p.providerKey,model:chosenModel!});const sealedCredentials=p.providerKey?encrypt({apiKey:p.providerKey,model:chosenModel},'mission:'+id,'AGENT_KEY_ENCRYPTION_KEY'):null;await sql().begin(async tx=>{await tx`SELECT id FROM principals WHERE id=${principal.id} FOR UPDATE`;await tx`SELECT pg_advisory_xact_lock(84532001)`;const [global]=await tx`SELECT count(*)::int AS n FROM missions WHERE created_at>now()-interval '24 hours'`;if(global.n>=Number(process.env.MAX_DAILY_MISSIONS??20))throw new Error('Global demo mission limit reached');const [active]=await tx`SELECT count(*)::int AS n FROM missions WHERE principal_id=${principal.id} AND created_at>now()-interval '24 hours'`;if(active.n>=5)throw new Error('Daily demo mission limit reached');await tx`INSERT INTO missions(id,principal_id,tenant_id,objective,brief,sports,package_budget_cents,budget_wei,gas_budget_wei,provider_credentials) VALUES(${id},${principal.id},${principal.tenantId},${p.objective},${p.brief},${tx.json(p.sports)},${p.packageBudgetCents},${p.researchBudgetWei},${p.gasBudgetWei},${sealedCredentials})`;await tx`INSERT INTO jobs(id,kind,payload) VALUES(${id},'buyer',${tx.json({missionId:id})})`});return getMission(principal,id)}
export async function getMission(principal:Principal,id:string){const [mission]=await sql()`SELECT * FROM missions WHERE id=${id} AND principal_id=${principal.id} AND tenant_id=${principal.tenantId}`;if(!mission)throw new Error('Mission not found');const activity=await sql()`SELECT id,actor,kind,summary,detail,created_at FROM mission_events WHERE mission_id=${id} ORDER BY id`;const orders=await sql()`SELECT id,offer_id,chain_order_id,funding_tx,delivery_tx,outcome_tx,withdrawal_tx,status FROM market_orders WHERE mission_id=${id} AND principal_id=${principal.id}`;const reservations=await sql()`SELECT offer_id,price_wei::text,status FROM budget_reservations WHERE mission_id=${id}`;const {provider_credentials:_sealed,...publicMission}=mission;return {...publicMission,id:mission.id as string,byok:!!_sealed,activity,orders,reservations}}
export async function stopMission(principal:Principal,id:string){await getMission(principal,id);await sql()`UPDATE missions SET status='stopped',provider_credentials=NULL,updated_at=now() WHERE id=${id} AND principal_id=${principal.id}`;return getMission(principal,id)}
export async function listPublicOffers(principal?:Principal){return sql()`SELECT id,event_id,manifest,chain_offer_id,publication_tx,status FROM offers WHERE manifest->>'version'='1' AND (allowed_principal IS NULL OR allowed_principal=${principal?.id??null}) ORDER BY event_id,id`}
export async function getHealth(){let database=false,worker=false;try{await sql()`SELECT 1`;database=true;const [alive]=await sql()`SELECT EXISTS(SELECT 1 FROM worker_health WHERE heartbeat_at>now()-interval '45 seconds') AS alive`;worker=alive.alive}catch{}const missing=['RPC_URL','MARKET_CONTRACT_ADDRESS','MARKET_BYTECODE_HASH','VERIFIER_PRIVATE_KEY'].filter(k=>!process.env[k]);const {platformCredentials}=await import('../agents/provider');const platform=platformCredentials();const byok=process.env.FORCE_BYOK==='true'||!platform;return {mode:process.env.DEMO_MODE??'live',chainId:84532,network:'Base Sepolia',confirmations:Math.max(2,Number(process.env.CONFIRMATIONS??2)),model:platform?.model??null,byok,database,worker,ready:database&&worker&&missing.length===0,missing,contract:process.env.MARKET_CONTRACT_ADDRESS??null,disclosure:'Synthetic data · custodial test wallets · platform-run deterministic verifier. L2 confirmation is not L1 finality.'}}
export async function activity(missionId:string,actor:string,kind:string,summary:string,detail:Record<string,unknown>={}){await sql()`INSERT INTO mission_events(mission_id,actor,kind,summary,detail) VALUES(${missionId},${actor},${kind},${summary.slice(0,500)},${sql().json(detail as any)})`}
export async function readPurchasedReport(principal:Principal,orderId:string):Promise<unknown>{const {readReport}=await import('./market');return readReport(principal,orderId)}
export async function getResearchWallet(principal:Principal){
 if(principal.role!=='buyer')throw new Error('Buyer authorization required');
 const {ensureWallet}=await import('./wallet');
 const wallet=await ensureWallet(principal.id,principal.tenantId,'buyer');
 const {createPublicClient,http}=await import('viem');
 const {baseSepolia}=await import('viem/chains');
 let balanceWei='0';
 try{const client=createPublicClient({chain:baseSepolia,transport:http(process.env.RPC_URL,{timeout:10000})});balanceWei=(await client.getBalance({address:wallet.address as `0x${string}`})).toString()}catch{}
 return {address:wallet.address,balanceWei,chainId:84532,explorer:'https://sepolia.basescan.org/address/'+wallet.address};
}
export async function requestCustomAnalysis(principal:Principal,input:unknown){const {customRequest}=await import('./market');return customRequest(principal,input)}
