'use client';
import {useState,useEffect} from 'react';
import {selectEvidence} from '../../../packages/domain/src/evidence-selection';
import {LockKeyhole, RotateCcw, Info, ArrowUpRight} from 'lucide-react';
import type {EventProperty, Metric, ReportCore} from '../../../packages/domain/src/index';
import {getSportPack} from '../../../packages/sports/src/index';
import {statusLabel,templateLabel} from './labels';
export function NativeWorkspace({event,cores,onCustom}:{event:EventProperty;cores:ReportCore[];onCustom:(event:EventProperty,blocks:string[],zone:string)=>void}){
 const edition=event.editions.filter(e=>e.completed).at(-1)!;
 const blocks=event.blocks.filter(b=>b.editionId===edition.id);
 const [selected,setSelected]=useState(blocks[0]!.id),[zone,setZone]=useState(event.zones[0]!.id),[layer,setLayer]=useState('rights'),[cohort,setCohort]=useState('all'),[inspect,setInspect]=useState<Metric|null>(null);
 const pack=getSportPack(event.sportId);const current=blocks.find(b=>b.id===selected)!;
 const selection=selectEvidence(cores,{eventId:event.id,editionId:edition.id,blockId:selected,zoneId:zone,...(cohort!=='all'?{category:cohort as 'paid'|'complimentary'|'hospitality'}:{})});const metrics=selection.metrics;
 useEffect(()=>setInspect(null),[selected,zone,cohort]);
 const chosenZone=event.zones.find(z=>z.id===zone)!;
 const running=event.sportId==='running',golf=event.sportId==='golf',tennis=event.sportId==='tennis',squash=event.sportId==='squash',soccer=event.sportId==='football_soccer';
 const activeIndex=blocks.findIndex(b=>b.id===selected);
 const packages=event.packages.filter(p=>p.zoneIds.includes(zone)&&p.blockIds.some(b=>b.endsWith(`b${activeIndex+1}`)));
 return <div className="native-workspace">
 <div className="scope-bar"><div><span className="eyebrow">{pack.label} / Historical {edition.year}</span><h2>{event.name}</h2><p>{pack.population}</p></div><button className="quiet" onClick={()=>{setSelected(blocks[0]!.id);setZone(event.zones[0]!.id);setCohort('all')}}><RotateCcw size={15}/> Reset scope</button></div>
 <div className="native-columns"><section className="panel"><div className="panel-heading"><h3>{running?'Distance & wave':golf?'Tournament day':squash?'Round & session':tennis?'Court & session':'Fixture calendar'}</h3><span className="tag">2025 season</span></div>
 {running?<div className="inline-controls"><label>Distance<select value={current.distance} onChange={e=>setSelected(blocks.find(b=>b.distance===e.target.value)!.id)}>{[...new Set(blocks.map(b=>b.distance))].map(d=><option key={d}>{d}</option>)}</select></label><label>Wave<select value={current.wave} onChange={e=>setSelected(blocks.find(b=>b.distance===current.distance&&b.wave===e.target.value)!.id)}>{blocks.filter(b=>b.distance===current.distance).map(b=><option key={b.id}>{b.wave}</option>)}</select></label></div>:null}
 <div className={squash?'session-grid':tennis?'court-matrix':'fixture-list'} role="group" aria-label="Historical scopes">{blocks.map((b,i)=><button key={b.id} className={selected===b.id?'scope selected':'scope'} aria-pressed={selected===b.id} onClick={()=>{setSelected(b.id);if(tennis&&b.court){const court=event.zones.find(z=>z.label===b.court);if(court)setZone(court.id)}}}><span className="scope-index">{golf?`DAY 0${i+1}`:squash?b.round:tennis?b.court:running?b.distance:`JUN ${12+i}`}</span><strong>{b.label}</strong><span>{b.rescheduled?'Rescheduled':running?`Wave ${b.wave}`:golf?'Day-pass holders':'Ticketed session'}</span></button>)}</div>
 <div className="coverage-strip"><Info size={14}/>{event.coverageDisclosure}</div>
 {!running&&<label className="field">Ticket type<select value={cohort} onChange={e=>setCohort(e.target.value)}><option value="all">All ticket types</option><option value="paid">Paid</option><option value="complimentary">Complimentary</option><option value="hospitality">Hospitality</option></select></label>}
 <p className="semantic-note">{pack.invalidEvidence}</p>
 </section><section className="panel"><div className="panel-heading"><h3>{running?'Route & measured touchpoints':golf?'Grounds & hospitality':tennis?'Campus access map':squash?'Court & hospitality':soccer?'Stadium & fan zone':'Arena sections'}</h3><span className="tag">Venue map</span></div>
 <div className="segmented"><button className={layer==='rights'?'active':''} onClick={()=>setLayer('rights')}>Access map</button><button className={layer==='evidence'?'active':''} onClick={()=>setLayer('evidence')}>Data view</button></div>
 <div className={`venue-map ${event.sportId}`}>
 <svg viewBox="0 0 420 245" aria-label="Public schematic geometry, not a surveyed layout" role="img">
 {running?<><path d="M45 170 Q100 40 180 100 T355 60 L365 180 Q260 220 180 155 T45 170" fill="none" stroke="currentColor" strokeWidth="8" strokeDasharray="9 5"/><text x="180" y="222">Route context only</text></>:golf?<><path d="M30 170 Q40 30 150 55 T350 60 Q410 170 300 195 T30 170Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M70 160 Q170 130 140 75 M180 170 Q240 80 325 100" stroke="currentColor" fill="none" strokeWidth="12" opacity=".22"/><text x="160" y="228">No hole-level tracking</text></>:<><rect x="75" y="35" width="270" height="165" rx={soccer||event.sportId==='basketball'?65:8} fill="none" stroke="currentColor" strokeWidth="2"/><rect x="150" y="74" width="120" height="83" fill="none" stroke="currentColor"/><path d="M210 74 V157 M150 115 H270" stroke="currentColor"/><text x="155" y="225">Public venue topology</text></>}
 </svg>
 {event.zones.map(z=>{const zoneMetrics=selectEvidence(cores,{eventId:event.id,editionId:edition.id,blockId:selected,zoneId:z.id,...(cohort!=='all'?{category:cohort as 'paid'|'complimentary'|'hospitality'}:{})}).metrics.filter(m=>m.zoneId===z.id);const measured=zoneMetrics.find(m=>m.status==='verified_purchased');return <button key={z.id} aria-pressed={zone===z.id} className={`map-marker ${zone===z.id?'selected':''}`} style={{left:`${z.x}%`,top:`${z.y}%`}} onClick={()=>setZone(z.id)}><span>{event.zones.indexOf(z)+1}</span>{z.label}{layer==='evidence'&&<small>{measured?`${measured.numerator}${measured.denominator!==undefined?' / '+measured.denominator:''}`:statusLabel(zoneMetrics[0]?.status??'')||'Not purchased'}</small>}</button>})}
 {layer==='evidence'&&!metrics.length&&<div className="map-lock"><LockKeyhole size={17}/> Numbers unlock with a purchased report</div>}
 </div>
 <div className="zone-list" aria-label="Accessible map locations">{event.zones.map((z,i)=><button key={z.id} aria-pressed={zone===z.id} className={zone===z.id?'selected':''} onClick={()=>setZone(z.id)}><b>{i+1}</b><span>{z.label}</span><small>{z.instrumented?'Tracked':'Not tracked'}</small></button>)}</div>
 <p className="semantic-note">{chosenZone.accessRule}. {layer==='rights'?'A ticket means someone could enter, not that they did.':'Only data you’ve purchased appears below.'}</p>
 </section></div>
 <section className="panel evidence-panel"><div className="panel-heading"><div><span className="eyebrow">The numbers</span><h3>{current.label} / {chosenZone.label}</h3></div><span className="tag">{metrics.length?'Purchased':'Not purchased'}</span></div>
 {metrics.length?<div className={running?'cohort-grid':'metric-grid'}>{metrics.map((m,i)=><button className="metric" key={`${m.id}-${i}`} onClick={()=>setInspect(m)}><span>{m.label}</span><strong>{m.status==='verified_purchased'?(m.denominator!==undefined?`${m.numerator} / ${m.denominator}`:m.value??m.numerator??'—'):statusLabel(m.status)}</strong><small>{m.unit}</small><Info size={14}/></button>)}</div>:<div className="locked-evidence"><LockKeyhole size={25}/><div><h4>{selection.sourceCores.length?'Your reports don’t cover this selection':'These numbers are for sale.'}</h4><p>{running?'Sign-ups, packet pickups, starts and finishes are counted separately. Full breakdowns unlock after purchase.':'How many tickets, how many were actually used, and the exact totals unlock after purchase.'}</p></div><button className="primary" onClick={()=>onCustom(event,[selected],zone)}>Get this data <ArrowUpRight size={16}/></button></div>}
 {metrics.some(m=>m.id.startsWith('arrival_'))&&<div className="arrival-chart" aria-label="Recorded first-entry time bins">{metrics.filter(m=>m.id.startsWith('arrival_')).map(m=><div key={m.id}><span>{m.label}</span>{m.status==='verified_purchased'&&m.value!==undefined?<><div className="bar-track"><div style={{width:`${m.value/100}%`}}/></div><b>{m.numerator} / {m.denominator}</b></>:<b>{m.status.replaceAll('_',' ')}</b>}</div>)}</div>}
 {selection.sourceCores.length>0&&<details><summary>Coverage & limitations</summary>{selection.sourceCores.map(c=><div key={c.snapshotId+c.templateId}><p className="semantic-note">{c.coverage.filter(v=>v.blockId===selected).map(v=>`${v.source}: ${statusLabel(v.status)}${v.reason?' · '+v.reason:''}`).join(' · ')}</p><p className="semantic-note">{c.limitations.join(' ')}</p></div>)}</details>}
 {selection.eventWide.length>0&&<div className="event-wide"><h4>Event-wide data · not tied to the selected area</h4>{selection.eventWide.map(m=><button className="secondary" key={m.id} onClick={()=>setInspect(m)}>{m.label}: {m.status==='verified_purchased'?`${m.numerator} / ${m.denominator}`:statusLabel(m.status)}</button>)}</div>}
 {inspect&&<div className="inspector"><button className="quiet" onClick={()=>setInspect(null)}>Close</button><h4>{inspect.label}</h4><dl>{Object.entries(inspect.definition).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{v}</dd></div>)}</dl></div>}
 </section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">From the organizer</span><h3>Sponsorship packages for this selection · 2027</h3></div></div>{packages.length?<div className="package-grid">{packages.map(p=><article key={p.id}><span className="tag">{p.activation.replaceAll('_',' ')}</span><h4>{p.name}</h4><strong className="package-price">${(p.priceCents/100).toLocaleString()}</strong><ul>{p.rights.map(r=><li key={r}>{r}</li>)}</ul><p>{p.restrictions.join(' · ')}</p></article>)}</div>:<p className="empty">No package covers this area and session.</p>}<p className="semantic-note">Past seasons don’t guarantee future results. Your agent recommends; the deal itself is confirmed with the organizer.</p></section>
 </div>
}
