'use client';
import {useState} from 'react';
import {EVENTS,getSportPack} from '../../../packages/sports/src/index';
import {parseImportCsv,importSchemas,type ImportTable} from '../../../packages/sports/src/imports';
import {availableTemplates} from '../../../packages/analytics/src/index';
import {tableLabel,templateLabel} from './labels';
export default function OrganizerWorkspace(){
 const [eventId,setEventId]=useState(EVENTS[0]!.id),[table,setTable]=useState<ImportTable>('accounts'),[csv,setCsv]=useState(''),[result,setResult]=useState<{ok:boolean;text:string}|null>(null);
 const event=EVENTS.find(e=>e.id===eventId)!,pack=getSportPack(event.sportId);const tables=(Object.keys(importSchemas) as ImportTable[]).filter(t=>event.sportId==='running'?t!=='entitlements':t!=='entries');
 const headers=Object.keys(importSchemas[table].shape);
 async function file(file:File|undefined){setResult(null);if(!file)return;if(file.size>2_000_000){setResult({ok:false,text:'File exceeds 2 MB. Choose a smaller source export.'});return}setCsv(await file.text())}
 function validate(){try{const validated=parseImportCsv(event,table,csv);setResult({ok:true,text:`Checked ${validated.rows.length} rows against the ${pack.label} format: types, scope and duplicates all pass. ${validated.warnings.join(' ')} Publishing runs through the secure organizer service.`})}catch(error){setResult({ok:false,text:error instanceof Error?error.message:'Validation failed'})}}
 return <div className="page-stack"><div className="section-intro"><span className="eyebrow">For event organizers</span><h1>Check your data before you sell it.</h1><p>Everything here stays in your browser. This view cannot read, replace or publish the private source inventory sold to buyers.</p></div><div className="native-columns"><section className="panel"><h2>Your data</h2><label className="field">Property<select value={eventId} onChange={e=>{setEventId(e.target.value);setTable('accounts');setResult(null);setCsv('')}}>{EVENTS.map(e=><option key={e.id} value={e.id}>{e.name} · {getSportPack(e.sportId).label}</option>)}</select></label><label className="field">Data type<select value={table} onChange={e=>{setTable(e.target.value as ImportTable);setResult(null);setCsv('')}}>{tables.map(t=><option key={t} value={t}>{tableLabel(t)}</option>)}</select></label><p className="semantic-note">Data format: {event.formatId.replaceAll('_',' ')} v{event.formatVersion} · Organizer: {event.organizerId}</p><label className="field">Upload a CSV<input type="file" accept=".csv,text/csv" onChange={e=>void file(e.target.files?.[0])}/></label><label className="field">Or paste CSV<textarea value={csv} maxLength={2_000_000} rows={8} onChange={e=>{setCsv(e.target.value);setResult(null)}} placeholder={headers.join(',')}/></label><button className="primary" disabled={!csv.trim()} onClick={validate}>Check my data</button>{result&&<div role="status" className={result.ok?'notice':'error'}><strong>{result.ok?'Looks good':'Something’s off'}</strong><p>{result.text}</p></div>}</section><section className="panel"><span className="eyebrow">Required columns</span><h2>{tableLabel(table)}</h2><code style={{overflowWrap:'anywhere'}}>{headers.join(', ')}</code><p>Only these columns are accepted. Missing buyer locations stay unknown rather than guessed, and scan records don’t assume every gate was covered.</p><h3>What your data can power</h3><p className="semantic-note">Based on this event’s declared setup, not this file alone.</p><div className="tags">{event.capabilities.map(c=><span key={c} className="tag">{c.replaceAll('_',' ')}</span>)}</div><h3>Reports you can sell</h3><ul>{availableTemplates(event).map(t=><li key={t}>{templateLabel(t)}</li>)}</ul><p>{pack.invalidEvidence}</p><h3>Publishing your data</h3><p>Signed-in organizers import checked data through the secure organizer service, review what it enables, and set prices and limits. Each import creates a locked snapshot; reports already sold keep the version they were sold from.</p></section></div></div>
}
