/** Executes the real backend against local Anvil only. Never a public-testnet receipt. */
import {writeFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
import {createWalletClient,http,type Hex} from 'viem';import {privateKeyToAccount} from 'viem/accounts';import {baseSepolia} from 'viem/chains';
import {sql,closeDatabase} from '../packages/database/index';import {createSession,createMission,readPurchasedReport} from '../packages/server/index';import {chain,ensureWallet} from '../packages/server/wallet';import {prepareOffer,publishOffer,purchaseOffer,fundOrder,fulfillOrder,acceptOrder,withdrawOrder,reportCommitment} from '../packages/server/market';import {decrypt,encrypt} from '../packages/server/crypto';import {EVENTS} from '../packages/sports/src/index';import {marketAbi} from '../packages/chain/index';import type {ReportCore} from '../packages/domain/src/index';
if(!process.env.DATABASE_URL?.includes('/sportproof_chain_test'))throw new Error('Isolated sportproof_chain_test database is mandatory');if(process.env.RPC_URL!=='http://127.0.0.1:18545'||!process.env.LOCAL_ADMIN_PRIVATE_KEY)throw new Error('Explicit local fixture required');process.env.DEMO_MODE='local-chain-fixture';const client=chain(),admin=createWalletClient({account:privateKeyToAccount(process.env.LOCAL_ADMIN_PRIVATE_KEY as Hex),chain:baseSepolia,transport:http(process.env.RPC_URL)});const fund=async(address:string)=>client.publicClient.request({method:'anvil_setBalance',params:[address,'0x56BC75E2D63100000']} as never);
async function retry<T>(fn:()=>Promise<T>):Promise<T>{for(let n=0;n<20;n++){try{return await fn()}catch(e){if(!/confirm|receipt|not found/i.test(String(e))||n===19)throw e;await new Promise(r=>setTimeout(r,1100))}}throw new Error('Retry exhausted')}
const {principal}=await createSession(),other=(await createSession()).principal;const buyer=await ensureWallet(principal.id,principal.tenantId,'buyer');await fund(buyer.address);const mission=await createMission(principal,{objective:'hospitality',brief:'Local backend integration across six sports',sports:['squash','tennis','basketball','football_soccer','running','golf'],packageBudgetCents:6000000,researchBudgetWei:'1000000000000000'});const results:unknown[]=[];
for(const sport of ['squash','tennis','basketball','football_soccer','running','golf','invalid'] as const){const event=sport==='invalid'?EVENTS.filter(e=>e.sportId==='squash')[1]!:EVENTS.find(e=>e.sportId===sport)!;const seller=await ensureWallet(null,event.organizerId,'seller');await fund(seller.address);const approval=await admin.writeContract({address:client.config.address,abi:marketAbi,functionName:'setSeller',args:[seller.address,true]});await client.publicClient.waitForTransactionReceipt({hash:approval});const scope={eventId:event.id,editionId:event.editions.filter(e=>e.completed).at(-1)!.id,templateId:sport==='running'?'participant_turnout_v1' as const:'ticket_usage_v1' as const,...(sport==='invalid'?{category:'paid' as const}:{})};const offer=await prepareOffer(event.organizerId,scope,principal.id) as {id:string};if(!offer.id)throw new Error('No prepared offer');if(sport==='invalid'){const [row]=await sql()`SELECT * FROM offers WHERE id=${offer.id}`;const envelope=decrypt<{core:ReportCore;salt:Hex}>(row.encrypted_artifact,row.id);const metric=envelope.core.metrics.find(m=>m.denominator!==undefined);if(!metric)throw new Error('Invalid fixture requires a denominator');metric.denominator!+=17;await sql()`UPDATE offers SET encrypted_artifact=${encrypt(envelope,row.id)},report_commitment=${reportCommitment(envelope.core,envelope.salt,row.terms_hash,row.manifest.datasetCommitment,seller.address)} WHERE id=${row.id}`;}
await retry(()=>publishOffer(offer.id));const order=await purchaseOffer(principal,mission.id,offer.id);let denied=false;try{await readPurchasedReport(principal,order.orderId)}catch{denied=true}if(!denied)throw new Error('Unpaid read leaked');await retry(()=>fundOrder(order.orderId));await retry(()=>fulfillOrder(order.orderId));if(sport!=='invalid'){const report:any=await readPurchasedReport(principal,order.orderId);if(report.core.sportId!==sport)throw new Error('Wrong sport core');let unauthorized=false;try{await readPurchasedReport(other,order.orderId)}catch{unauthorized=true}if(!unauthorized)throw new Error('Cross-buyer leak');await retry(()=>acceptOrder(principal,order.orderId));}await retry(()=>withdrawOrder(order.orderId));const [row]=await sql()`SELECT id,chain_order_id,funding_tx,delivery_tx,outcome_tx,withdrawal_tx,status FROM market_orders WHERE id=${order.orderId}`;results.push({sport,...row});}
await writeFile('.local/backend-integration-results.json',JSON.stringify({environment:'LOCAL Anvil only; chain ID 84532 is not evidence of public deployment',runId:randomUUID(),results},null,2));console.log('PASS: six real local-chain backend paid lifecycles; invalid committed denominator refunded; unauthorized/unpaid reads denied. Receipts in ignored .local/backend-integration-results.json.');await closeDatabase();
