/** LOCAL ONLY fixture operator: creates ignored secret env and funds local Anvil wallets. */
import {readFile,writeFile} from 'node:fs/promises';
import {createPublicClient,createWalletClient,http,keccak256,type Hex} from 'viem';import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';import {baseSepolia} from 'viem/chains';import {sql,closeDatabase} from '../packages/database/index';
const rpc='http://127.0.0.1:18545';const p=createPublicClient({chain:baseSepolia,transport:http(rpc)});const adminKey=generatePrivateKey(),verifierKey=(process.env.VERIFIER_PRIVATE_KEY||generatePrivateKey()) as Hex;const admin=privateKeyToAccount(adminKey),verifier=privateKeyToAccount(verifierKey);
const request=(method:string,params:unknown[])=>p.request({method,params} as never);
await request('anvil_setBalance',[admin.address,'0x56BC75E2D63100000']);await request('anvil_setBalance',[verifier.address,'0x56BC75E2D63100000']);
const artifact=JSON.parse(await readFile('contracts/out/SportProofMarket.sol/SportProofMarket.json','utf8'));const w=createWalletClient({account:admin,chain:baseSepolia,transport:http(rpc)});const hash=await w.deployContract({abi:artifact.abi,bytecode:artifact.bytecode.object,args:[admin.address,verifier.address]});const r=await p.waitForTransactionReceipt({hash});const address=r.contractAddress!;const code=(await p.getCode({address}))!;
const wallets=await sql()`SELECT address,role FROM agent_wallets`;for(const row of wallets){await request('anvil_setBalance',[row.address,'0x56BC75E2D63100000']);if(row.role==='seller'){const h=await w.writeContract({address,abi:artifact.abi,functionName:'setSeller',args:[row.address,true]});await p.waitForTransactionReceipt({hash:h});}}
await writeFile('.local/chain.env',[`RPC_URL=${rpc}`,`MARKET_CONTRACT_ADDRESS=${address}`,`MARKET_BYTECODE_HASH=${keccak256(code)}`,`MARKET_DEPLOYMENT_BLOCK=${r.blockNumber}`,`VERIFIER_PRIVATE_KEY=${verifierKey}`,`LOCAL_ADMIN_PRIVATE_KEY=${adminKey}`,'CONFIRMATIONS=2',''].join('\n'),{mode:0o600});
console.log('LOCAL Anvil fixture prepared; secrets only in ignored .local/chain.env. Existing DB wallets funded and sellers approved. Not a public deployment.');await closeDatabase();
