import { z } from 'zod';
import type { EventProperty, Snapshot } from '../../domain/src/index';
const id=z.string().min(1).max(180),date=z.string().datetime();
export const importSchemas={
 accounts:z.object({id,organizerId:id,region:z.enum(['Bay Metro','North Coast','Inland']).nullable()}).strict(),
 purchases:z.object({id,accountId:id,editionId:id,status:z.enum(['paid','refunded'])}).strict(),
 entitlements:z.object({id,ticketId:id,accountId:id,editionId:id,blockId:id,zoneId:id,category:z.enum(['paid','complimentary','hospitality']),product:z.enum(['single','series','group','complimentary','grounds','weekly']),status:z.enum(['valid','refunded','void']),scheduleVersion:z.coerce.number().int().positive()}).strict(),
 entries:z.object({id,participantId:id,accountId:id,editionId:id,blockId:id,status:z.enum(['valid','cancelled','transferred']),version:z.coerce.number().int().positive(),bib:id}).strict(),
 observations:z.object({id,subjectId:id,blockId:id,zoneId:id,kind:z.enum(['gate','court','hospitality','activation','pickup','start','finish']),at:date,accepted:z.union([z.boolean(),z.enum(['true','false']).transform(v=>v==='true')]),scheduleVersion:z.coerce.number().int().positive()}).strict(),
 coverage:z.object({blockId:id,source:z.enum(['gate','court','hospitality','activation','pickup','start','finish']),zoneId:id.optional(),status:z.enum(['complete','partial','not_collected']),from:date,to:date,reason:z.string().max(250).optional()}).strict()
};
export type ImportTable=keyof typeof importSchemas;
export function validateImport(event:EventProperty,table:ImportTable,rows:unknown[]){if(rows.length>20000)throw new Error('Import row cap exceeded');if(event.sportId==='running'&&table==='entitlements'||event.sportId!=='running'&&table==='entries')throw new Error('Source table is incompatible with this reviewed format');const parsed=rows.map(row=>importSchemas[table].parse(row));const keys=new Set<string>();for(const row of parsed){if('id'in row){if(keys.has(row.id))throw new Error('Duplicate source key');keys.add(row.id)}if('organizerId'in row&&row.organizerId!==event.organizerId)throw new Error('Cross-tenant account rejected');if('blockId'in row&&!event.blocks.some(b=>b.id===row.blockId&&b.editionId.endsWith('2024')||b.id===row.blockId&&b.editionId.endsWith('2025')))throw new Error('Unknown/commercial-future block cannot be imported as history');if('zoneId'in row&&row.zoneId&&!event.zones.some(z=>z.id===row.zoneId))throw new Error('Unknown measured zone');}return {table,rows:parsed,synthetic:true as const,warnings:table==='observations'?['Observations alone do not establish complete coverage.']:[]}}
export function reconcileSnapshot(s:Snapshot){const errors:string[]=[];const entitlementKeys=new Set<string>(),entryKeys=new Set<string>();for(const p of s.purchases)if(!s.accounts.some(a=>a.id===p.accountId))errors.push('purchase_missing_account');for(const e of s.entitlements){if(!s.accounts.some(a=>a.id===e.accountId))errors.push('entitlement_missing_account');if(!s.blocks.some(b=>b.id===e.blockId&&b.editionId===e.editionId))errors.push('entitlement_missing_block');if(!s.zones.some(z=>z.id===e.zoneId))errors.push('entitlement_missing_zone');const key=e.ticketId+':'+e.blockId+':'+e.zoneId;if(e.status==='valid'&&entitlementKeys.has(key))errors.push('duplicate_valid_entitlement');if(e.status==='valid')entitlementKeys.add(key)}for(const e of s.entries){if(!s.accounts.some(a=>a.id===e.accountId))errors.push('entry_missing_account');if(!s.blocks.some(b=>b.id===e.blockId&&b.editionId===e.editionId))errors.push('entry_missing_block');const key=e.participantId+':'+e.editionId+':'+e.blockId;if(e.status==='valid'&&entryKeys.has(key))errors.push('duplicate_valid_participant_entry');if(e.status==='valid')entryKeys.add(key)}for(const o of s.observations){if(!s.blocks.some(b=>b.id===o.blockId)||!s.zones.some(z=>z.id===o.zoneId))errors.push('observation_unknown_scope');if(o.kind==='activation')continue;const ids=['pickup','start','finish'].includes(o.kind)?s.entries:s.entitlements;const subject=ids.find(x=>x.id===o.subjectId);if(!subject)errors.push('orphan_observation');else if(subject.blockId!==o.blockId)errors.push('observation_subject_scope_mismatch')}for(const c of s.coverage){if(!s.blocks.some(b=>b.id===c.blockId)||c.zoneId&&!s.zones.some(z=>z.id===c.zoneId))errors.push('coverage_unknown_scope');if(Date.parse(c.from)>=Date.parse(c.to))errors.push('coverage_invalid_interval')}return {valid:errors.length===0,errors:[...new Set(errors)]}}

/** Bounded RFC-4180-style generated-source CSV import. No code/formula evaluation. */
export function parseImportCsv(event:EventProperty,table:ImportTable,csv:string){
 if(typeof csv!=='string'||new TextEncoder().encode(csv).byteLength>2_000_000)throw new Error('CSV size exceeds 2 MB');
 const records:string[][]=[];let row:string[]=[],cell='',quoted=false,closed=false;
 const pushCell=()=>{row.push(cell);cell='';closed=false};const pushRow=()=>{pushCell();if(row.some(v=>v!==''))records.push(row);row=[];if(records.length>20001)throw new Error('Import row cap exceeded')};
 for(let i=0;i<csv.length;i++){const c=csv[i]!;if(quoted){if(c==='"'){if(csv[i+1]==='"'){cell+='"';i++}else{quoted=false;closed=true}}else cell+=c;continue}if(c==='"'){if(cell||closed)throw new Error('Invalid CSV quoting');quoted=true}else if(c===',')pushCell();else if(c==='\n')pushRow();else if(c==='\r'){if(csv[i+1]==='\n')i++;pushRow()}else {if(closed)throw new Error('Unexpected data after quoted field');cell+=c}}
 if(quoted)throw new Error('Unclosed CSV quote');if(cell||row.length)pushRow();const headers=records.shift();if(!headers||!headers.length)throw new Error('CSV header required');headers[0]=headers[0]!.replace(/^\uFEFF/,'');if(new Set(headers).size!==headers.length||headers.some(h=>!h||['__proto__','constructor','prototype'].includes(h)))throw new Error('Invalid or duplicate CSV header');
 const objects=records.map(r=>{if(r.length!==headers.length)throw new Error('CSV row width does not match header');return Object.fromEntries(headers.map((h,i)=>[h,h==='region'&&r[i]===''?null:r[i]===''&&['zoneId','reason'].includes(h)?undefined:r[i]]))});return validateImport(event,table,objects);
}
