import type { Capability, EventProperty, SportId, TemplateId } from '../../domain/src/index';
export interface SportPack {id:SportId;version:'1';label:string;formats:string[];templates:TemplateId[];nativeView:string;population:string;customQuestion:string;invalidEvidence:string;sourceTables:string[]}
const shared:TemplateId[]=['returning_buyers_v1','buyer_geography_v1','session_package_fit_v1'];
const ticketed:TemplateId[]=[...shared,'ticket_usage_v1','ticket_product_usage_v1','arrival_window_v1','hospitality_access_v1','activation_zone_usage_v1'];
export const SPORT_PACKS:SportPack[]=[
{id:'squash',version:'1',label:'Squash',formats:['court_tournament'],templates:[...ticketed,'court_session_usage_v1'],nativeView:'round-session-grid',population:'Ticket holders by session',customQuestion:'Compare premium ticket use across the semifinal and final sessions, separating paid and complimentary tickets.',invalidEvidence:'A gate scan shows someone entered the session, not that they watched every match.',sourceTables:['entitlements','observations','coverage','blocks','zones']},
{id:'tennis',version:'1',label:'Tennis',formats:['campus_tournament'],templates:[...ticketed,'court_session_usage_v1','court_access_usage_v1'],nativeView:'court-session-campus',population:'Ticket holders plus separate court-access passes',customQuestion:'Compare stadium-session attendance with separately measured booth interactions on the grounds.',invalidEvidence:'Entering the grounds doesn\u2019t mean every court was visited.',sourceTables:['entitlements','observations','coverage','blocks','zones']},
{id:'basketball',version:'1',label:'Basketball',formats:['fixture_series'],templates:[...ticketed,'fixture_usage_v1'],nativeView:'fixture-section-arena',population:'Ticket holders by match',customQuestion:'Compare the three-game premium package with independently measured lounge visits.',invalidEvidence:'A transferred season ticket doesn\u2019t create extra seats.',sourceTables:['entitlements','transfers','observations','coverage','blocks','zones']},
{id:'football_soccer',version:'1',label:'Soccer',formats:['fixture_series'],templates:[...ticketed,'fixture_usage_v1'],nativeView:'kickoff-sector-fanzone',population:'Ticket holders by match',customQuestion:'Compare pre-kickoff arrival times with independent fan-zone interactions.',invalidEvidence:'Arrival times for a rescheduled match are measured against the new kickoff, not the original one.',sourceTables:['entitlements','observations','coverage','blocks','zones']},
{id:'running',version:'1',label:'Running',formats:['adult_road_race'],templates:[...shared,'participant_turnout_v1','participant_return_v1','activation_zone_usage_v1'],nativeView:'distance-wave-cohorts',population:'Race entries by distance',customQuestion:'Compare independently recorded expo booth interactions with finish-area interactions.',invalidEvidence:'Picking up a race packet isn\u2019t the same as starting the race.',sourceTables:['entries','transfers','observations','coverage','blocks','zones']},
{id:'golf',version:'1',label:'Golf',formats:['multi_day_tournament'],templates:[...ticketed,'day_pass_usage_v1'],nativeView:'day-course-hospitality',population:'Day-pass holders',customQuestion:'Compare measured hospitality attendance across tournament days, separate from grounds admissions.',invalidEvidence:'A grounds scan doesn\u2019t prove hospitality access or which holes were watched.',sourceTables:['entitlements','observations','coverage','blocks','zones']}
];
export function getSportPack(id:string){const p=SPORT_PACKS.find(p=>p.id===id);if(!p)throw new Error('Unsupported sport pack');return p}
const pairs:Record<SportId,string[]>= {squash:['Glasscourt Invitational','Harbor Squash Open'],tennis:['Riverside Tennis Week','Juniper Court Classic'],basketball:['Metro Hoops Showcase','Foundry Basketball Series'],football_soccer:['Portside Football Cup','Valley Soccer Series'],running:['Waterfront Half Marathon','Ridgeline Road Festival'],golf:['Meadow Links Invitational','Pinewater Golf Classic']};
export const EVENTS:EventProperty[]=SPORT_PACKS.flatMap((pack,pi)=>pairs[pack.id].map((name,i)=>{
 const id=name.toLowerCase().replace(/\s+/g,'-');const native=pack.id==='running'?'race':pack.id==='golf'?'day':['basketball','football_soccer'].includes(pack.id)?'fixture':'session';
 const labels=pack.id==='squash'?['Quarterfinal afternoon','Semifinal evening','Final evening']:pack.id==='tennis'?['Stadium day','Outer-court day','Stadium night','Outer-court night']:pack.id==='basketball'?['vs Alloy • Friday','vs Comets • Saturday','vs Sparks • Sunday']:pack.id==='football_soccer'?['vs Estuary • Group','vs Valley • Rescheduled','vs Summit • Final']:pack.id==='running'?['5K • Wave A','Half marathon • Wave A','Half marathon • Wave B']:['Practice day','Round one','Final round'];
 const editions=[2024,2025,2027].map(year=>({id:`${id}-${year}`,year,completed:year<2026}));
 const blocks=editions.flatMap(e=>labels.map((label,b)=>({id:`${e.id}-b${b+1}`,label,kind:native as 'race'|'day'|'fixture'|'session',start:`${e.year}-06-${String(12+(pack.id==='tennis'?Math.floor(b/2):b)).padStart(2,'0')}T${pack.id==='tennis'&&b>=2?'20':'18'}:00:00Z`,end:`${e.year}-06-${String(12+(pack.id==='tennis'?Math.floor(b/2):b)).padStart(2,'0')}T23:00:00Z`,scheduleVersion:pack.id==='football_soccer'&&b===1?2:1,editionId:e.id,...(pack.id==='squash'?{round:['Quarterfinal','Semifinal','Final'][b],court:'Glass court'}:{}),...(pack.id==='tennis'?{court:b%2===1?'Outer court':'Stadium court'}:{}),...(['basketball','football_soccer'].includes(pack.id)?{opponent:['Alloy','Comets','Summit'][b],rescheduled:pack.id==='football_soccer'&&b===1}:{}),...(pack.id==='running'?{distance:b===0?'5K':'21.1K',wave:b===2?'B':'A'}:{})})));
 const zoneLabels=pack.id==='running'?['Expo','Finish area','Course context']:pack.id==='tennis'?['Stadium court','Outer court','Grounds activation']:pack.id==='basketball'?['Lower bowl','Upper bowl','Premium lounge']:pack.id==='football_soccer'?['Home-designated sector','Away-designated sector','Fan zone']:pack.id==='golf'?['Grounds','Club hospitality','Practice green']:['Glass court','Side court','Hospitality lounge'];
 const zones=zoneLabels.map((label,z)=>({id:`${id}-z${z+1}`,label,kind:(pack.id==='running'?(z===0?'expo':z===1?'finish':'grounds'):z===2?(pack.id==='football_soccer'||pack.id==='tennis'?'activation':pack.id==='golf'?'grounds':'hospitality'):pack.id==='golf'?(z===1?'hospitality':'grounds'):['basketball','football_soccer'].includes(pack.id)?'section':'court') as EventProperty['zones'][number]['kind'],x:[20,68,44][z]!,y:[28,32,76][z]!,instrumented:i===0 || z===0,accessRule:z===2?'Sponsor activation area (needs separate organizer approval)':'Ticket or pass required'}));
 const capabilities:Capability[]=pack.id==='running'?['entries','pickups','timing','participant_history','account_history','account_geography']:['entitlements','gate_scans','account_history','account_geography','products','arrival_times'];
 if(['basketball','football_soccer'].includes(pack.id))capabilities.push('fixtures');if(pack.id==='tennis')capabilities.push('court_access');if(pack.id==='golf')capabilities.push('days');if(i===0){capabilities.push('activation');if(pack.id!=='running')capabilities.push('hospitality')}
 const upcoming=editions[2]!.id;const packages=[{id:`${id}-host`,name:pack.id==='running'?'Expo sampling partnership':'Hosted partner experience',priceCents:(35000+i*12000+pi*1500)*100,activation:pack.id==='running'?'participant_sampling':'hospitality',blockIds:blocks.filter(b=>b.editionId===upcoming).map(b=>b.id),zoneIds:[zones[pack.id==='golf'?1:pack.id==='running'?0:2]!.id],rights:['Organizer-declared category placement','Staffed activation space','Pre-agreed access credentials'],restrictions:['No inferred personal profiles','Category exclusivity subject to commercial review'],available:true,editionId:upcoming},{id:`${id}-demo`,name:pack.id==='running'?'Finish-area sampling':'On-site demonstration',priceCents:(22000+i*5000)*100,activation:pack.id==='running'?'participant_sampling':'demonstration',blockIds:[`${upcoming}-b3`],zoneIds:[zones[pack.id==='running'?1:2]!.id],rights:['Organizer-declared staffed demonstration area'],restrictions:['No guaranteed impressions','No commercial agreement signed by agents'],available:true,editionId:upcoming}] as EventProperty['packages'];
 return {id,name,sportId:pack.id,formatId:pack.formats[0]!,formatVersion:'1',organizerId:`organizer-${pack.id}`,organizerName:`${pack.label} Civic Events`,location:i===0?'Bay Metro':'North Coast',description:`Fictional ${pack.label.toLowerCase()} property. Historical 2024–2025 evidence; separate 2027 sponsorship inventory.`,synthetic:true,capabilities,editions,blocks,zones,packages,coverageDisclosure:i===0?'Most sessions and areas are tracked; a few may have partial data.':'Only main gates and timing points are tracked; no booth-level tracking.',customQuestion:pack.customQuestion};
}));
export function getEvent(id:string){const event=EVENTS.find(e=>e.id===id);if(!event)throw new Error('Unknown fictional property');return event}
